const COURSES = {
  國文: { icon: "文", color: "blue", intro: "閱讀、寫作、字詞與古典文本的理解策略", units: ["字音字形與詞義", "修辭與句型判讀", "記敘、說明、議論文本", "文言文與文化常識"] },
  英文: { icon: "A", color: "orange", intro: "字彙、文法、閱讀與生活溝通", units: ["生活字彙與片語", "時態與句型", "閱讀理解策略", "聽說情境與寫作"] },
  數學: { icon: "π", color: "teal", intro: "用圖形、數字與規律解決問題", units: ["數與數線", "代數式與方程式", "幾何與測量", "函數、統計與機率"] },
  自然: { icon: "⚗", color: "purple", intro: "生物、理化與地球科學的觀察、推理與實驗", units: ["生物與人體系統", "物質、粒子與化學反應", "力、運動、能量與電", "地球環境與宇宙"] },
  社會: { icon: "⌘", color: "pink", intro: "歷史、地理、公民的時間、空間與制度思考", units: ["臺灣史、中國史與世界史", "地圖、區域與人地互動", "政府、法律與公民生活", "經濟、文化與全球議題"] }
};
const GRADE_UNITS = {
  7:{國文:["字音字形與詞義","修辭與句型判讀","記敘、說明、議論文本","文言文與文化常識"],英文:["生活字彙與片語","現在式與進行式","基本句型與問答","生活閱讀理解"],數學:["數與數線","指數記法與科學記號","一元一次方程式","幾何圖形與三視圖"],自然:["生物與人體系統","生態系與生物分類","物質、粒子與化學反應","地球環境與宇宙"],社會:["臺灣史、中國史與世界史","地圖、區域與人地互動","政府、法律與公民生活","經濟、文化與全球議題"]},
  8:{國文:["字詞、成語與語法","古典詩文閱讀","抒情與議論寫作","跨文本比較閱讀"],英文:["過去式與比較級","未來式與情態助動詞","連接詞與段落閱讀","生活情境表達"],數學:["乘法公式與多項式","平方根與畢氏定理","一元二次方程式","資料分析與機率"],自然:["細胞、生殖與遺傳","力、運動、能量與電","光、聲與波動","氣候與地球系統"],社會:["近代臺灣與東亞","人口、產業與區域發展","法律、權利與責任","市場、金融與公共選擇"]},
  9:{國文:["國學常識與文言統整","論證與批判閱讀","寫作表達與修辭應用","跨文本素養題"],英文:["完成式與被動語態","關係子句與分詞","篇章結構與推論","會考閱讀與寫作"],數學:["二次函數與圖形","相似形與圓","三角比與生活應用","統計、機率與資料判讀"],自然:["神經、恆定與演化","酸鹼鹽與化學反應","電磁、能源與科技","天文、地質與永續"],社會:["現代臺灣與世界","全球化與區域議題","民主政治與公共參與","永續發展與跨科素養"]}
};
const LESSONS = {
  "自然:生物與人體系統": { title:"心臟與血液循環", type:"heart", key:"血液透過心臟的收縮，被送往肺部交換氣體，再由左心室送往全身。", question:"哪一個構造會將含氧血送往全身？", answers:["右心房","右心室","左心室","肺動脈"], correct:2, explanation:"左心室肌肉最厚，收縮時將含氧血經由主動脈送往全身。" },
  "數學:函數、統計與機率": { title:"一次函數的圖形", type:"math", key:"斜率描述 x 每增加 1，y 改變多少；截距是直線與 y 軸相交的位置。", question:"當斜率由 1 變成 3，直線會如何改變？", answers:["更平坦","更陡峭","向下移動","與 y 軸平行"], correct:1, explanation:"正斜率越大，x 每增加 1 時 y 增加得越快，因此線會更陡。" },
  "自然:力、運動、能量與電": { title:"串聯與並聯電路", type:"lab", key:"串聯電路只有一條路徑；並聯電路有多條支路，某一支路斷開時其他支路仍可運作。", question:"家中的燈通常採用哪種連接方式？", answers:["串聯","並聯","兩者都不能","沒有電路"], correct:1, explanation:"家用電器採並聯，才能各自開關且不會因一盞燈壞掉而全部熄滅。" },
  "社會:臺灣史、中國史與世界史": { title:"朝代與世界變遷", type:"timeline", key:"年表不是背日期，而是找出事件的先後、同時性與因果關係。", question:"使用年表整理歷史，最能幫助我們理解什麼？", answers:["只記住更多年份","事件的先後與關聯","每個人的生日","只背人物名字"], correct:1, explanation:"把事件放在同一條時間線上，可以觀察哪些事件同時發生，並思考前後因果。" },
  "國文:記敘、說明、議論文本": { title:"閱讀文章的觀點與證據", type:"text", key:"議論文本通常包含主張、理由與證據。閱讀時先找作者要你相信什麼，再檢查證據是否支持主張。", question:"下列哪一項最適合用來支持一個主張？", answers:["與主題無關的形容詞","可查證的資料或例子","重複一次主張","完全不同的故事"], correct:1, explanation:"可查證的資料與相關例子能形成理由，支持作者的主張。" },
  "英文:時態與句型": { title:"現在完成式的時間線", type:"text", key:"現在完成式連結過去與現在，常用來說明經驗、剛完成的事，或持續到現在的狀態。", question:"Which sentence expresses an experience?", answers:["I went to Tainan yesterday.","I have visited Tainan twice.","I am visiting Tainan now.","I will visit Tainan tomorrow."], correct:1, explanation:"have visited 表示至今累積的經驗，沒有指定單一完成時間。" },
  "社會:地圖、區域與人地互動": { title:"用地圖理解人與環境", type:"text", key:"地圖將真實空間依比例、符號與方向縮小呈現；閱讀時要先看圖例、方向與比例尺。", question:"地圖上的圖例主要告訴讀者什麼？", answers:["繪圖者的名字","符號代表的意義","地圖的價格","閱讀時間"], correct:1, explanation:"圖例解釋地圖中的顏色、線條與符號，才能正確讀取資訊。" },
  "數學:幾何與測量": { title:"三角形的角與邊", type:"text", key:"三角形內角和固定為 180°。畫圖、標記已知量，再用關係式推理，比直接背公式更可靠。", question:"一個三角形已有兩角 50° 與 60°，第三角是多少？", answers:["60°","70°","80°","90°"], correct:1, explanation:"180° − 50° − 60° = 70°。" }
};
const state = { view:"home", grade:7, subject:"自然", lesson:null, data:loadData() };
function loadData(){ try { return JSON.parse(localStorage.getItem("learning-star-data")) || { notes:{}, completed:{}, answers:{} }; } catch { return {notes:{},completed:{},answers:{}}; } }
function save(){ localStorage.setItem("learning-star-data", JSON.stringify(state.data)); }
function notify(message){ const t=document.querySelector("#toast"); t.textContent=message; t.classList.add("show"); clearTimeout(notify.timer); notify.timer=setTimeout(()=>t.classList.remove("show"),2600); }
function escapeHtml(value=""){ return value.replace(/[&<>'"]/g, c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;","\"":"&quot;"}[c])); }
function courseKey(subject,unit){ return `${subject}:${unit}`; }
function pickLesson(subject,unit){ return LESSONS[courseKey(subject,unit)] || { title:unit, type:"text", key:`這是「${unit}」的學習起點。先用例子理解概念，將重點記成自己的話，再透過練習確認是否真的會用。`, question:"完成本節後，最好的複習方法是？", answers:["只看標題","用自己的話整理並做練習","跳過不懂的地方","只背答案"], correct:1, explanation:"能用自己的話說明並應用在題目上，才表示真正理解。" }; }
function completedCount(){ return Object.keys(state.data.completed).length; }
function render(){ document.querySelectorAll(".nav-link").forEach(b=>b.classList.toggle("active",b.dataset.view===state.view)); const app=document.querySelector("#app"); app.innerHTML=state.view==="home"?homeView():state.view==="courses"?coursesView():state.view==="notebook"?notebookView():lessonView(); bind(); app.focus({preventScroll:true}); }
function homeView(){ const lessons=[pickLesson("自然","生物與人體系統"),pickLesson("數學","函數、統計與機率"),pickLesson("社會","臺灣史、中國史與世界史")]; return `<section class="hero"><div class="hero-copy"><div class="eyebrow">今天，也把不懂的變成看得見的</div><h1>從一個觀念開始，<br>畫出你的學習星圖。</h1><p>讀重點、親手操作互動教材、記下自己的理解，再用練習確認。所有紀錄都安全地保留在這台裝置。</p></div><div class="hero-stat"><span>本機學習進度</span><strong>${completedCount()} <small>/ 15</small></strong><span>完成一小節，就是一顆星。</span></div></section><div class="section-head"><div><div class="eyebrow">五大學習領域</div><h2>選一科，開始探索</h2></div><button class="secondary" data-action="courses">查看完整課程地圖</button></div><section class="subject-grid">${Object.entries(COURSES).map(([name,c])=>`<button class="subject-card ${c.color}" data-subject="${name}"><em>${c.icon}</em><b>${name}</b><small>${c.intro.split("、")[0]} · ${c.units.length} 大主題</small></button>`).join("")}</section><section class="dashboard-grid"><div class="card"><div class="section-head"><div><div class="eyebrow">推薦下一步</div><h2>把概念變具體</h2></div></div>${lessons.map((l,i)=>`<div class="lesson-row"><span class="lesson-icon">${["♥","↗","◷"][i]}</span><div><b>${l.title}</b><small>${l.key.slice(0,28)}…</small></div><button class="secondary" data-open="${["自然:生物與人體系統","數學:函數、統計與機率","社會:臺灣史、中國史與世界史"][i]}">開始</button></div>`).join("")}</div><aside class="card"><div class="eyebrow">學習方式</div><h2>不是背下來，是理解</h2><div class="progress-ring" style="--progress:${Math.min(completedCount()/15*100,100)}"><span>${completedCount()}</span></div><ul class="tiny-list"><li>操作模型或圖形</li><li>用自己的話留下筆記</li><li>用題目驗證理解</li></ul></aside></section>`; }
function coursesView(){ const c=COURSES[state.subject]; const units=GRADE_UNITS[state.grade][state.subject]; return `<div class="course-layout"><aside class="course-side"><div class="card"><div class="eyebrow">選擇年級</div><div class="grade-tabs">${[7,8,9].map(n=>`<button class="chip ${state.grade===n?"active":""}" data-grade="${n}">${n} 年級</button>`).join("")}</div><div class="eyebrow">選擇科目</div><div class="course-list">${Object.keys(COURSES).map(n=>`<button class="${n===state.subject?"active":""}" data-subject="${n}">${COURSES[n].icon}　${n}</button>`).join("")}</div></div></aside><section class="course-content"><div class="eyebrow">${state.grade} 年級 · ${state.subject}</div><h1>${state.subject}課程地圖</h1><p>${c.intro}。選擇主題後，可閱讀重點、進行互動探索並留下筆記。</p><div class="unit-grid">${units.map((u,i)=>{const k=courseKey(`${state.grade}年級 ${state.subject}`,u), l=pickLesson(state.subject,u),done=!!state.data.completed[k];return `<article class="unit"><span class="tag">單元 ${String(i+1).padStart(2,"0")}</span><h3>${u}</h3><p>${l.title}：${l.key.slice(0,42)}…</p><footer><span>${done?"✓ 已完成":"◎ 待探索"}</span><button class="primary" data-open="${k}" data-grade-open="${state.grade}">進入單元</button></footer></article>`}).join("")}</div></section></div>`; }
function visual(lesson){ if(lesson.type==="heart")return `<div class="visual-box"><h3>立體心臟模型</h3><p>拖動按鈕切換視角，點選構造，再追蹤橘色血液的流動。</p><div class="heart-stage"><div class="heart-model" id="heartModel"><button class="heart-part atrium left-atrium" data-part="左心房" aria-label="左心房"></button><button class="heart-part atrium right-atrium" data-part="右心房" aria-label="右心房"></button><button class="heart-part ventricle left-ventricle" data-part="左心室" aria-label="左心室"></button><button class="heart-part ventricle right-ventricle" data-part="右心室" aria-label="右心室"></button><button class="heart-part artery" data-part="主動脈" aria-label="主動脈"></button><button class="heart-part vein" data-part="腔靜脈" aria-label="腔靜脈"></button><i class="flow-dot"></i></div></div><div class="control-row"><button data-rotate="0" class="active">正面</button><button data-rotate="-35">左側</button><button data-rotate="35">右側</button><button data-flow>血流動畫</button></div><div class="explain" id="partExplain">點選心臟構造：右側收集來自全身的血液，左側將含氧血送向全身。</div></div>`;
if(lesson.type==="math")return `<div class="visual-box"><h3>動手改變斜率</h3><p>移動滑桿後，先預測直線會變陡還是變平，再觀察圖形。</p><div class="math-stage"><i class="axis-x"></i><i class="axis-y"></i><i class="line" id="functionLine" style="--slope:-21deg"></i><i class="point" style="--x:67%;--y:29%"></i></div><label class="range-wrap">斜率 <input id="slope" type="range" min="-4" max="4" value="1" /><output id="slopeOut">1</output></label><div class="explain" id="mathExplain">斜率 = 1：x 每增加 1，y 增加 1。試著調成負數，看看方向如何改變。</div></div>`;
if(lesson.type==="lab")return `<div class="visual-box"><h3>電路實驗桌</h3><p>切換接法，觀察其中一個燈泡壞掉時，其他燈是否還亮著。</p><div class="lab"><div class="lab-item"><b>燈泡 A</b><div class="meter"><span id="bulbA" style="--value:100%"></span></div></div><div class="lab-item"><b>燈泡 B</b><div class="meter"><span id="bulbB" style="--value:100%"></span></div></div></div><div class="control-row"><button data-circuit="parallel" class="active">並聯</button><button data-circuit="series">串聯</button><button data-break>讓燈泡 A 斷開</button></div><div class="explain" id="labExplain">並聯有不同支路，A 斷開時 B 仍然可以發亮。</div></div>`;
if(lesson.type==="timeline")return `<div class="visual-box"><h3>時間不是一串日期</h3><p>選擇節點，觀察同一時期不同地區的事件與它們的關聯。</p><div class="timeline">${["清代治理臺灣","工業革命","臺灣開港","甲午戰爭","日治時期"].map((e,i)=>`<button class="event ${i===2?"active":""}" data-event="${i}"><i></i>${e}</button>`).join("")}</div><div class="explain" id="timeExplain">臺灣開港（1860）讓臺灣更直接進入世界貿易網絡；同一時期，工業革命已改變歐洲的生產與交通。</div></div>`;
return `<div class="visual-box"><h3>先讀懂，再記住</h3><p>把關鍵概念說成自己的話；如果能舉一個生活例子，就真的開始理解了。</p><div class="explain">提示：閱讀時可問自己「作者／題目在說什麼？為什麼？有什麼例子能證明？」把答案寫到右側筆記。</div></div>`; }
function lessonView(){ const lesson=state.lesson; const key=lesson.key, note=state.data.notes[key]||"",done=!!state.data.completed[key]; return `<button class="crumb" data-action="courses">← 回到課程地圖</button><div class="lesson-layout"><article><div class="eyebrow">${lesson.subject} · ${lesson.unit}</div><h1 class="lesson-title">${lesson.title}</h1><p class="lesson-intro">本節先將觀念具體化，再將你的發現寫下來。完成互動與練習後，可標記為已學會。</p><div class="concept"><b>本節核心：</b>${lesson.key}</div>${visual(lesson)}<section class="question card"><div class="eyebrow">立即驗證</div><h2>${lesson.question}</h2><div class="answers">${lesson.answers.map((a,i)=>`<button class="answer" data-answer="${i}">${String.fromCharCode(65+i)}. ${a}</button>`).join("")}</div><div id="feedback"></div></section></article><aside class="sidebar-note"><section class="card"><div class="eyebrow">我的理解</div><h2>筆記小卡</h2><textarea class="note-area" id="noteArea" placeholder="用自己的話寫下重點、疑問或例子…">${escapeHtml(note)}</textarea><p class="note-status" id="noteStatus">自動儲存於這台裝置</p><button class="primary" id="completeButton">${done?"✓ 已標記為學會":"標記為我已學會"}</button></section></aside></div>`; }
function notebookView(){ const notes=Object.entries(state.data.notes).filter(([,n])=>n.trim()); return `<div class="section-head"><div><div class="eyebrow">你的學習痕跡</div><h1>我的筆記</h1><p>這些內容只保存在目前瀏覽器；請定期匯出備份。</p></div><button class="secondary" id="exportButton">匯出 JSON</button></div><div class="note-list">${notes.length?notes.map(([key,n])=>{const [subject,unit]=key.split(":");return `<article class="card note-card"><div class="eyebrow">${subject}</div><h3>${unit}</h3><p>${escapeHtml(n)}</p><button class="secondary" data-open="${key}">回到單元</button></article>`}).join(""):`<div class="card empty">還沒有筆記。進入任一單元，將你的理解寫下來吧。</div>`}</div>`; }
function openLesson(key){ let [subject,unit]=key.split(":"); const gradeMatch=subject.match(/^(\d+)年級 (.+)$/); if(gradeMatch){state.grade=+gradeMatch[1];subject=gradeMatch[2];} const base=pickLesson(subject,unit); state.lesson={...base,subject,unit,key}; state.subject=subject; state.view="lesson"; render(); }
function bind(){ document.querySelectorAll(".nav-link").forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render();}); document.querySelectorAll("[data-subject]").forEach(b=>b.onclick=()=>{state.subject=b.dataset.subject;state.view="courses";render();}); document.querySelectorAll("[data-grade]").forEach(b=>b.onclick=()=>{state.grade=+b.dataset.grade;render();}); document.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openLesson(b.dataset.open)); document.querySelectorAll("[data-action='courses']").forEach(b=>b.onclick=()=>{state.view="courses";render();}); document.querySelector("#exportButton")?.addEventListener("click",exportData); document.querySelector("#noteArea")?.addEventListener("input",e=>{state.data.notes[state.lesson.key]=e.target.value;save();document.querySelector("#noteStatus").textContent="已自動儲存";}); document.querySelector("#completeButton")?.addEventListener("click",()=>{state.data.completed[state.lesson.key]=true;save();notify("太好了！已把這一節加入學習進度。");render();}); document.querySelectorAll("[data-answer]").forEach(b=>b.onclick=()=>answer(+b.dataset.answer)); bindVisual(); }
function solvingTip(lesson){ const tips={"自然":"先找出題目問的是『構造、現象還是原因』，再用流程圖追蹤變化；不要只靠名詞的字面意思猜答案。","數學":"先把題目的已知條件標在圖或式子上，再使用關係式逐步計算；最後把答案代回檢查是否合理。","社會":"先抓時間、地點與主題三個線索，再比較事件的先後與因果；不要只孤立地背年代或名詞。","國文":"先找作者的主張，再找能支持主張的理由或證據；選項若只是重複、無關或情緒化描述，通常不是答案。","英文":"先看句子要表達的時間與語意，再找對應的動詞形式；不要只憑看到熟悉單字就作答。"}; return tips[lesson.subject]||"先圈出題目真正要問的概念，用自己的話說明理由，再回頭排除不符合條件的選項。"; }
function answer(choice){ const l=state.lesson,feedback=document.querySelector("#feedback"),correctAnswer=l.answers[l.correct];document.querySelectorAll(".answer").forEach((b,i)=>{b.classList.toggle("correct",i===l.correct);b.classList.toggle("wrong",i===choice&&i!==l.correct);}); state.data.answers[l.key]=choice;save();feedback.innerHTML=`<div class="feedback"><b>${choice===l.correct?"答對了，也要知道為什麼。":"這題先別急著背，跟著解題步驟看一次。"}</b><br><b>正確答案：</b>${String.fromCharCode(65+l.correct)}. ${correctAnswer}<br><b>觀念原理：</b>${l.explanation}<br><b>解題技巧：</b>${solvingTip(l)}</div>`; }
function bindVisual(){ document.querySelectorAll("[data-rotate]").forEach(b=>b.onclick=()=>{document.querySelector("#heartModel").style.transform=`rotateY(${b.dataset.rotate}deg) rotateX(-8deg)`;document.querySelectorAll("[data-rotate]").forEach(x=>x.classList.toggle("active",x===b));}); document.querySelectorAll("[data-part]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-part]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");document.querySelector("#partExplain").textContent=({"左心房":"左心房接收從肺部回流的含氧血。","右心房":"右心房接收從全身回流、含氧較少的血液。","左心室":"左心室將含氧血強力送入主動脈，前往全身。","右心室":"右心室將血液送往肺部進行氣體交換。","主動脈":"主動脈是將含氧血送往全身的大血管。","腔靜脈":"腔靜脈把全身回流的血液帶回右心房。"})[b.dataset.part];}); document.querySelector("[data-flow]")?.addEventListener("click",()=>{const d=document.querySelector(".flow-dot");d.style.animation="none";requestAnimationFrame(()=>d.style.animation="flow 3s infinite");notify("正在追蹤血液流動路徑");}); document.querySelector("#slope")?.addEventListener("input",e=>{const v=+e.target.value;document.querySelector("#slopeOut").value=v;document.querySelector("#functionLine").style.setProperty("--slope",`${-v*18}deg`);document.querySelector("#mathExplain").textContent=v===0?"斜率 = 0：這是一條水平線，y 不會隨 x 改變。":`斜率 = ${v}：x 每增加 1，y ${v>0?"增加":"減少"} ${Math.abs(v)}。`;}); let circuit="parallel",broken=false;document.querySelectorAll("[data-circuit]").forEach(b=>b.onclick=()=>{circuit=b.dataset.circuit;broken=false;document.querySelectorAll("[data-circuit]").forEach(x=>x.classList.toggle("active",x===b));document.querySelector("#bulbA").style.width="100%";document.querySelector("#bulbB").style.width="100%";document.querySelector("#labExplain").textContent=circuit==="parallel"?"並聯有不同支路，A 斷開時 B 仍然可以發亮。":"串聯只有一條路徑，任一處斷開會使整個電路中斷。";});document.querySelector("[data-break]")?.addEventListener("click",()=>{broken=true;document.querySelector("#bulbA").style.width="0%";document.querySelector("#bulbB").style.width=circuit==="series"?"0%":"100%";document.querySelector("#labExplain").textContent=circuit==="series"?"A 斷開後，電流無法形成完整迴路，B 也熄滅。":"A 的支路斷開，但 B 還有自己的路徑，因此仍亮著。";});document.querySelectorAll("[data-event]").forEach(b=>b.onclick=()=>{document.querySelectorAll(".event").forEach(x=>x.classList.toggle("active",x===b));const info=["清代治理臺灣：制度與移民活動影響臺灣社會發展。","工業革命：機械化生產與交通革新改變全球貿易。","臺灣開港：臺灣更直接進入世界貿易網絡。","甲午戰爭：東亞局勢改變，臺灣的統治者也隨之變動。","日治時期：現代制度與基礎建設帶來社會變化。"];document.querySelector("#timeExplain").textContent=info[+b.dataset.event];}); }
function exportData(){ const blob=new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),data:state.data},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="學習星圖備份.json";a.click();URL.revokeObjectURL(a.href);notify("備份檔已下載。"); }
document.querySelector("#backupButton").onclick=()=>{const choice=confirm("按「確定」匯出備份；按「取消」選擇備份檔匯入。");if(choice)exportData();else document.querySelector("#importInput").click();};document.querySelector("#importInput").onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const json=JSON.parse(await file.text());if(!json?.data?.notes||!json?.data?.completed)throw Error();if(!confirm("匯入將以備份檔取代目前的本機學習資料，是否繼續？"))return;state.data=json.data;save();notify("已成功匯入備份。");render();}catch{notify("這不是可用的學習星圖備份檔。 ");}e.target.value="";};
render();
