/* 每一個章節頁都帶有該學科的互動工作臺與原創整理筆記。 */
(() => {
  const app = document.querySelector('#app'); if (!app) return;
  const subjectAdvice = {
    數學:{method:'先把條件放到數線、圖或式子，再逐步運算；每一步保留理由。',trap:'不要只看數字外觀或直接移項；先確認符號、單位與基準。',mode:'數量與關係圖'},
    自然:{method:'先圈出改變、控制、量測三種變因，再用模型說因果。',trap:'現象是證據，不等於原因；不要把一次觀察當成完整結論。',mode:'科學因果流程'},
    英文:{method:'先看句子想表達的時間、人物和任務，再選結構與字詞。',trap:'不能只看單一熟悉單字；要把整句與情境一起讀。',mode:'句子情境組裝'},
    國文:{method:'先抓句子或段落的中心，再找能支持它的詞句與表達效果。',trap:'不要把修辭名稱當答案；還要說明它如何影響意思或語氣。',mode:'文本證據連線'},
    社會:{method:'先定位時間、地點、角色，再連結制度、環境與影響。',trap:'不能只背名詞年份；必須回答背景、事件與改變的關係。',mode:'時間空間因果圖'}
  };
  const q=(s,r=document)=>r.querySelector(s);
  const sourceGuide={
    數學:['公開學生筆記常用「數線、符號表、因數樹、面積模型」整理數學；本站將它們改寫為可操作模型與原創題目。','https://www.clearnotebooks.com/zh-TW/notebooks/2307671'],
    國文:['公開筆記常以注釋、句意重組與主張—證據框架協助閱讀；本站以原創文本與判讀流程呈現，不轉載筆記內容。','https://www.clearnotebooks.com/zh-TW/notebooks/2446570'],
    英文:['公開筆記常把時態畫成時間線、將句型拆成結構；本站以原創例句與互動結構圖重新編寫。','https://www.clearnotebooks.com/zh-TW/notebooks/2017113'],
    自然:['公開筆記常以流程圖、比較表整理生物、理化與地科；本站以因果模型、實驗變因與原創檢核題重新編寫。','https://www.clearnotebooks.com/zh-TW/notebooks/grade/junior-high/subject/science'],
    社會:['公開會考整理常以地圖、年表、制度關係與案例表格組織資料；本站以原創事件鏈與讀圖流程重編。','https://www.clearnotebooks.com/zh-TW/notebooks/1698681']
  };
  const esc=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  function absoluteValueLab(){
    return `<div class="interactive-visual absolute-lab" data-absolute-lab><div class="visual-instruction">拖曳 x：位置在 0 的哪一側？距離又是多少？</div><label class="visual-slider-label">x 的位置 <input type="range" min="-8" max="8" value="-4" step="1" data-absolute-slider><output data-absolute-output>x = −4</output></label><svg class="absolute-svg" data-absolute-svg viewBox="0 0 640 180" role="img" aria-label="可調整的數線與絕對值距離圖"></svg><div class="visual-status" data-absolute-readout>−4 在 0 的左邊；從 0 到 −4 有 4 格，所以 |−4| = 4。</div></div>`;
  }
  function renderAbsolute(lab){
    const input=q('[data-absolute-slider]',lab); if(!input)return;
    const value=Number(input.value), abs=Math.abs(value), svg=q('[data-absolute-svg]',lab), output=q('[data-absolute-output]',lab), readout=q('[data-absolute-readout]',lab);
    const left=54, width=532, zero=left+width/2, unit=width/16, x=zero+value*unit;
    const ticks=Array.from({length:17},(_,i)=>{const n=i-8,px=left+i*unit;return `<g><line x1="${px}" y1="92" x2="${px}" y2="${n===0?116:108}" class="${n===0?'zero-tick':'tick'}"/><text x="${px}" y="139">${n}</text></g>`}).join('');
    svg.innerHTML=`<defs><marker id="abs-arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto"><path d="M0,0 L0,6 L6,3z"/></marker></defs><line class="number-axis" x1="${left}" y1="92" x2="${left+width}" y2="92" marker-end="url(#abs-arrow)"/>${ticks}<line class="distance-line" x1="${zero}" y1="62" x2="${x}" y2="62"/><line class="distance-guide" x1="${zero}" y1="62" x2="${zero}" y2="92"/><line class="distance-guide" x1="${x}" y1="62" x2="${x}" y2="92"/><circle class="zero-dot" cx="${zero}" cy="92" r="7"/><circle class="value-dot" cx="${x}" cy="92" r="12"/><text class="distance-label" x="${(zero+x)/2}" y="45">距離 ${abs} 格</text><text class="value-label" x="${x}" y="170">x = ${value}</text>`;
    output.textContent=`x = ${value<0?'−'+abs:value}`;
    readout.textContent=`${value===0?'x 就在原點，距離是 0 格。':`${value<0?'負':'正'}數 ${value<0?'−'+abs:abs} ${value<0?'在左':'在右'}邊；從 0 到 x 有 ${abs} 格，所以 |${value<0?'−'+abs:abs}| = ${abs}。`}`;
  }
  function integerAdditionLab(){
    return `<div class="interactive-visual integer-lab" data-integer-lab><div class="integer-equation" data-integer-equation>−2 ＋ 5 ＝ 3</div><div class="integer-controls"><label>起點 <input type="range" min="-8" max="8" value="-2" step="1" data-integer-start><output data-integer-start-out>−2</output></label><label>加上 <input type="range" min="-8" max="8" value="5" step="1" data-integer-change><output data-integer-change-out>＋5</output></label></div><div class="visual-instruction">紫點是起點；箭頭向右代表加正數、向左代表加負數；橘點就是答案。</div><svg class="integer-svg" data-integer-svg viewBox="0 0 690 205" role="img" aria-label="整數加減的可調整數線"></svg><div class="visual-status" data-integer-readout>從 −2 出發，加上 ＋5 就向右走 5 格，停在 3。</div></div>`;
  }
  function signed(value,withPlus=false){return value<0?`−${Math.abs(value)}`:(withPlus?`＋${value}`:`${value}`);}
  function renderInteger(lab){
    const start=Number(q('[data-integer-start]',lab).value), change=Number(q('[data-integer-change]',lab).value), end=start+change;
    const min=-12,max=12,left=36,width=618,unit=width/(max-min),px=n=>left+(n-min)*unit, svg=q('[data-integer-svg]',lab);
    const ticks=Array.from({length:max-min+1},(_,i)=>{const n=min+i,x=px(n);return `<g><line x1="${x}" y1="120" x2="${x}" y2="${n===0?146:136}" class="${n===0?'zero-tick':'tick'}"/><text x="${x}" y="170">${n}</text></g>`}).join('');
    const sx=px(start), ex=px(end), within=end>=min&&end<=max;
    svg.innerHTML=`<defs><marker id="integer-arrow" markerWidth="10" markerHeight="10" refX="7" refY="4" orient="auto"><path d="M0,0 L0,8 L8,4z" fill="#e58232"/></marker></defs><line class="number-axis" x1="${left}" y1="120" x2="${left+width}" y2="120"/>${ticks}${within?`<path class="move-arrow" d="M ${sx} 76 Q ${(sx+ex)/2} ${Math.max(20,76-Math.abs(ex-sx)*.14)} ${ex} 76" marker-end="url(#integer-arrow)"/><circle class="start-dot" cx="${sx}" cy="120" r="13"/><circle class="end-dot" cx="${ex}" cy="120" r="13"/><text class="start-label" x="${sx}" y="48">起點 ${signed(start)}</text><text class="end-label" x="${ex}" y="202">答案 ${signed(end)}</text>`:`<text class="end-label" x="345" y="70">答案超出目前數線範圍</text>`}`;
    q('[data-integer-equation]',lab).textContent=`${signed(start)} ＋ ${signed(change,true)} ＝ ${signed(end)}`;
    q('[data-integer-start-out]',lab).textContent=signed(start);q('[data-integer-change-out]',lab).textContent=signed(change,true);
    q('[data-integer-readout]',lab).textContent=`從 ${signed(start)} 出發，加上 ${signed(change,true)}，所以${change>=0?'向右':'向左'}走 ${Math.abs(change)} 格，停在 ${signed(end)}。`;
  }
  function mathDiagram(kind,equation){
    if(kind==='signTable')return `<div class="sign-table"><span>×／÷</span><b>＋</b><b>−</b><b>＋</b><strong>＋</strong><strong>−</strong><b>−</b><strong>−</strong><strong>＋</strong></div>`;
    if(kind==='exponent')return `<div class="power-tiles"><i>底數</i><b>2</b><em>×</em><b>2</b><em>×</em><b>2</b><i>重複相乘</i></div>`;
    if(kind==='factorTree')return `<div class="factor-tree"><b>60</b><span>↙　↘</span><b>2</b><b>30</b><span>　　↙　↘</span><i>2 × 2 × 3 × 5</i></div>`;
    if(kind==='fractionBar')return `<div class="fraction-bars"><div><b style="--parts:3;--fill:2"></b><span>2／3</span></div><em>×／＋</em><div><b style="--parts:4;--fill:3"></b><span>3／4</span></div></div>`;
    if(kind==='algebraTiles')return `<div class="algebra-tiles"><b>x</b><b>x</b><b>x</b><i>＋</i><span>1</span><span>1</span><span>1</span><p>同類項才可以合併</p></div>`;
    if(kind==='balance')return `<div class="balance-diagram"><div class="balance-pan">3x − 5</div><div class="balance-pivot">＝</div><div class="balance-pan">10</div><p>兩邊做相同運算，天平才平衡</p></div>`;
    if(kind==='coordinate')return `<svg class="coordinate-diagram" viewBox="0 0 360 180" role="img" aria-label="座標平面"><path d="M25 150H340M180 15V165"/><path class="coord-line" d="M55 142L305 35"/><circle cx="180" cy="89" r="7"/><text x="315" y="28">y</text><text x="342" y="165">x</text><text x="188" y="84">關係點</text></svg>`;
    if(kind==='geometry')return `<svg class="geometry-diagram" viewBox="0 0 340 180" role="img" aria-label="幾何圖形"><path d="M42 145L150 28L286 145Z"/><path class="right-angle" d="M126 119h22v-22"/><text x="82" y="92">a</text><text x="210" y="93">b</text><text x="156" y="155">c</text><text x="152" y="25">直角／對應關係</text></svg>`;
    return `<div class="data-diagram"><i style="--h:35%"></i><i style="--h:68%"></i><i style="--h:48%"></i><i style="--h:86%"></i><b>比較高度、總數與比例</b></div>`;
  }
  function mathVisual(title, equation, explanation, kind){
    return `<div class="interactive-visual math-visual kind-${kind}" data-math-visual><div class="math-model-label">${esc(title)}</div><div class="math-canvas">${mathDiagram(kind,equation)}</div><div class="math-expression">${esc(equation)}</div><div class="visual-controls"><button type="button" data-math-step="0">看圖中條件</button><button type="button" data-math-step="1">操作關係</button><button type="button" data-math-step="2">代回驗證</button></div><div class="visual-status" data-math-status>先指出圖中每個量代表什麼，再開始運算。</div></div>`;
  }
  function signRuleLab(){
    return `<div class="interactive-visual sign-rule-lab" data-sign-rule-lab><div class="visual-instruction">先選兩個數的正負號；表格會直接算出乘除後的符號。</div><div class="visual-controls"><button data-sign-a="1" class="is-active">第一個：＋</button><button data-sign-a="-1">第一個：−</button><button data-sign-b="1" class="is-active">第二個：＋</button><button data-sign-b="-1">第二個：−</button></div><svg class="fraction-svg" data-sign-svg viewBox="0 0 520 180" role="img" aria-label="整數乘除符號規則模型"></svg><div class="fraction-result" data-sign-result></div></div>`;
  }
  function renderSignRule(lab){const a=Number(lab.dataset.a||1),b=Number(lab.dataset.b||1),same=a===b,svg=q('[data-sign-svg]',lab);svg.innerHTML=`<text class="fraction-title" x="260" y="34">${a>0?'＋':'−'}　×／÷　${b>0?'＋':'−'}</text><circle class="${a>0?'fraction-vertical':'fraction-horizontal'}" cx="150" cy="93" r="35"/><circle class="${b>0?'fraction-vertical':'fraction-horizontal'}" cx="260" cy="93" r="35"/><path d="M310 93h65" stroke="#526c83" stroke-width="5"/><text class="fraction-answer" x="423" y="104">${same?'＋':'−'}</text>`;q('[data-sign-result]',lab).textContent=`${same?'同號相乘或相除，結果為正；':'異號相乘或相除，結果為負；'}接著只要計算兩個數的絕對值。`;}
  function exponentLab(title){const scientific=title==='科學記號';return `<div class="interactive-visual exponent-lab" data-exponent-lab data-exponent-mode="${scientific?'scientific':'power'}"><div class="visual-instruction">${scientific?'拖曳小數點移動的格數；數字會改寫成科學記號。':'調整底數與指數；每一塊代表一次重複相乘。'}</div><div class="fraction-controls"><label>${scientific?'有效數字':'底數'} <input type="range" min="2" max="9" value="${scientific?3:2}" data-exponent-base><output data-exponent-base-out></output></label><label>${scientific?'移動格數':'指數'} <input type="range" min="${scientific?-6:1}" max="${scientific?6:5}" value="${scientific?4:3}" data-exponent-count><output data-exponent-count-out></output></label></div><svg class="fraction-svg" data-exponent-svg viewBox="0 0 620 220" role="img" aria-label="可調整指數與科學記號的模型"></svg><div class="fraction-result" data-exponent-result></div></div>`;}
  function renderExponent(lab){const base=Number(q('[data-exponent-base]',lab).value),count=Number(q('[data-exponent-count]',lab).value),science=lab.dataset.exponentMode==='scientific',svg=q('[data-exponent-svg]',lab);q('[data-exponent-base-out]',lab).textContent=base;q('[data-exponent-count-out]',lab).textContent=count>0?`＋${count}`:count;if(science){const value=base*Math.pow(10,count),raw=count>=0?`${base}${'0'.repeat(count)}`:`${base/Math.pow(10,-count)}`;const dots=Array.from({length:Math.abs(count)+1},(_,i)=>`<circle class="${i===Math.abs(count)?'fraction-overlap':'fraction-empty'}" cx="${130+i*58}" cy="105" r="18"/>`).join('');svg.innerHTML=`<text class="fraction-title" x="310" y="35">小數點移動 ${Math.abs(count)} 格</text><text class="fraction-answer" x="310" y="78">${raw} ＝ ${base} × 10${count<0?'⁻':''}${Math.abs(count)}</text>${dots}<text x="310" y="174">${count>=0?'向右：數變大':'向左：數變小'}</text>`;q('[data-exponent-result]',lab).textContent=`${raw} 可寫成 ${base} × 10${count<0?'⁻':''}${Math.abs(count)}；移動的格數就是 10 的指數。`;}else{const product=Math.pow(base,count),tiles=Array.from({length:count},(_,i)=>`<rect class="fraction-${i===count-1?'overlap':'vertical'}" x="${95+i*85}" y="75" width="58" height="58" rx="8"/><text x="${124+i*85}" y="111">${base}</text>${i<count-1?`<text x="${161+i*85}" y="111">×</text>`:''}`).join('');svg.innerHTML=`<text class="fraction-title" x="310" y="35">${base}${count===1?'':` 的 ${count} 次方`}</text>${tiles}<text class="fraction-answer" x="310" y="180">${base}${count===1?'':`^${count}`} ＝ ${product}</text>`;q('[data-exponent-result]',lab).textContent=`${base}${count===1?'':`^${count}`} 不是 ${base} × ${count}；它是 ${base} 連乘 ${count} 次，結果是 ${product}。`;}}
  function primeFactors(n){const factors=[];for(let p=2;p*p<=n;p+=(p===2?1:2))while(n%p===0){factors.push(p);n/=p;}if(n>1)factors.push(n);return factors;}
  function factorLab(title){const pair=title==='最大公因數與最小公倍數';return `<div class="interactive-visual factor-lab" data-factor-lab data-factor-pair="${pair}"><div class="visual-instruction">${pair?'調整兩數，顏色相同的是共同質因數；比較次方可找最大公因數與最小公倍數。':'調整一個整數，模型會拆到每個葉端都是質數。'}</div><div class="fraction-controls"><label>數 A <input type="range" min="12" max="96" value="${pair?12:60}" step="1" data-factor-a><output data-factor-a-out></output></label>${pair?'<label>數 B <input type="range" min="12" max="96" value="18" step="1" data-factor-b><output data-factor-b-out></output></label>':''}</div><svg class="fraction-svg" data-factor-svg viewBox="0 0 620 230" role="img" aria-label="可調整質因數分解模型"></svg><div class="fraction-result" data-factor-result></div></div>`;}
  function renderFactor(lab){const a=Number(q('[data-factor-a]',lab).value),pair=lab.dataset.factorPair==='true',b=pair?Number(q('[data-factor-b]',lab).value):0,fa=primeFactors(a),fb=pair?primeFactors(b):[];q('[data-factor-a-out]',lab).textContent=a;if(pair)q('[data-factor-b-out]',lab).textContent=b;const tokens=(factors,y,other)=>factors.map((x,i)=>`<rect class="${other.includes(x)&&factors.slice(0,i+1).filter(v=>v===x).length<=other.filter(v=>v===x).length?'fraction-overlap':'fraction-vertical'}" x="${80+i*70}" y="${y}" width="48" height="48" rx="9"/><text x="${104+i*70}" y="${y+31}">${x}</text>`).join('');const svg=q('[data-factor-svg]',lab);if(pair){const common=primeFactors(gcd(a,b)),g=gcd(a,b),l=lcm(a,b);svg.innerHTML=`<text class="fraction-title" x="310" y="30">共同質因數以紫色標示</text><text x="40" y="89">${a}＝</text>${tokens(fa,62,fb)}<text x="40" y="159">${b}＝</text>${tokens(fb,132,fa)}<text class="fraction-answer" x="310" y="214">最大公因數 ${g}　｜　最小公倍數 ${l}</text>`;q('[data-factor-result]',lab).textContent=`共同且次方較小的質因數相乘：GCF＝${g}；所有質因數取較大次方相乘：LCM＝${l}。`;}else{svg.innerHTML=`<text class="fraction-title" x="310" y="32">${a} 的質因數葉端</text><circle class="fraction-first" cx="310" cy="75" r="27"/><text x="310" y="81">${a}</text><path d="M310 105v20" stroke="#526c83" stroke-width="4"/>${tokens(fa,140,[])}<text class="fraction-answer" x="310" y="215">${fa.join(' × ')} ＝ ${a}</text>`;q('[data-factor-result]',lab).textContent=`${a} 拆成 ${fa.join(' × ')}；每一個葉端都是質數，而且相乘會回到原數。`;}}
  function algebraLab(title){const formula=title==='乘法公式';return `<div class="interactive-visual algebra-lab" data-algebra-lab data-algebra-formula="${formula}"><div class="visual-instruction">${formula?'拖曳 a、b；正方形會分成 a²、2ab、b² 三種面積。':'拖曳 x 的係數與常數；同類積木會聚成最後的式子。'}</div><div class="fraction-controls"><label>${formula?'a':'x 的係數'} <input type="range" min="1" max="6" value="${formula?3:3}" data-algebra-a><output data-algebra-a-out></output></label><label>${formula?'b':'常數'} <input type="range" min="1" max="6" value="${formula?2:2}" data-algebra-b><output data-algebra-b-out></output></label></div><svg class="fraction-svg" data-algebra-svg viewBox="0 0 620 250" role="img" aria-label="可調整代數積木與面積模型"></svg><div class="fraction-result" data-algebra-result></div></div>`;}
  function renderAlgebra(lab){const a=Number(q('[data-algebra-a]',lab).value),b=Number(q('[data-algebra-b]',lab).value),formula=lab.dataset.algebraFormula==='true',svg=q('[data-algebra-svg]',lab);q('[data-algebra-a-out]',lab).textContent=a;q('[data-algebra-b-out]',lab).textContent=b;if(formula){const total=a+b,scale=170/total,as=a*scale,bs=b*scale;svg.innerHTML=`<text class="fraction-title" x="310" y="28">邊長 (${a}＋${b}) 的正方形</text><rect class="fraction-overlap" x="210" y="48" width="${as}" height="${as}"/><rect class="fraction-vertical" x="${210+as}" y="48" width="${bs}" height="${as}"/><rect class="fraction-vertical" x="210" y="${48+as}" width="${as}" height="${bs}"/><rect class="fraction-horizontal" x="${210+as}" y="${48+as}" width="${bs}" height="${bs}"/><text x="${210+as/2}" y="${48+as/2}">a²</text><text x="${210+as+bs/2}" y="${48+as/2}">ab</text><text x="${210+as/2}" y="${48+as+bs/2}">ab</text><text x="${210+as+bs/2}" y="${48+as+bs/2}">b²</text><text class="fraction-answer" x="310" y="238">(${a}＋${b})² ＝ ${a*a} ＋ ${2*a*b} ＋ ${b*b} ＝ ${total*total}</text>`;q('[data-algebra-result]',lab).textContent=`四塊面積合起來：a²＋2ab＋b²；中間兩塊都是 ab，不能漏掉。`;}else{const xs=Array.from({length:a},(_,i)=>`<rect class="fraction-overlap" x="${95+i*55}" y="70" width="42" height="92" rx="3"/><text x="${116+i*55}" y="120">x</text>`).join(''),cs=Array.from({length:b},(_,i)=>`<rect class="fraction-horizontal" x="${95+i*55}" y="178" width="42" height="28" rx="3"/><text x="${116+i*55}" y="198">1</text>`).join('');svg.innerHTML=`<text class="fraction-title" x="310" y="28">同類項分別合併</text>${xs}${cs}<text class="fraction-answer" x="310" y="238">${a}x ＋ ${b}</text>`;q('[data-algebra-result]',lab).textContent=`有 ${a} 塊 x 積木和 ${b} 塊 1 積木，所以結果是 ${a}x＋${b}；x 與 1 不是同類項，不能相加成單一數字。`;}}
  function coordinateLab(title){const quad=title.includes('二次函數');return `<div class="interactive-visual coordinate-lab" data-coordinate-lab data-coordinate-quad="${quad}"><div class="visual-instruction">拖曳係數；圖上的線／拋物線、交點與對稱軸會同步改變。</div><div class="fraction-controls"><label>a <input type="range" min="-4" max="4" value="${quad?1:2}" step="1" data-coordinate-a><output data-coordinate-a-out></output></label><label>${quad?'k':'b'} <input type="range" min="-5" max="5" value="1" step="1" data-coordinate-b><output data-coordinate-b-out></output></label></div><svg class="fraction-svg" data-coordinate-svg viewBox="0 0 620 280" role="img" aria-label="可調整座標圖形"></svg><div class="fraction-result" data-coordinate-result></div></div>`;}
  function renderCoordinate(lab){let a=Number(q('[data-coordinate-a]',lab).value),b=Number(q('[data-coordinate-b]',lab).value),quad=lab.dataset.coordinateQuad==='true';if(a===0)a=1;q('[data-coordinate-a-out]',lab).textContent=a;q('[data-coordinate-b-out]',lab).textContent=b;const sx=x=>310+x*35,sy=y=>140-y*20,grid=Array.from({length:17},(_,i)=>{const n=i-8;return `<path d="M${sx(n)} 25V255M30 ${sy(n)}H590" stroke="#dbe6ef"/>`;}).join(''),points=Array.from({length:17},(_,i)=>{const x=i-8,y=quad?a*x*x+b:a*x+b;return `${i?'L':'M'}${sx(x)} ${sy(y)}`;}).join(''),svg=q('[data-coordinate-svg]',lab);svg.innerHTML=`${grid}<path d="M30 140H590M310 25V255" stroke="#486783" stroke-width="3"/><path d="${points}" fill="none" stroke="#e18434" stroke-width="5"/><circle class="fraction-overlap" cx="${sx(0)}" cy="${sy(b)}" r="7"/><text class="fraction-title" x="310" y="20">${quad?`y＝${a}x² ${b>=0?'＋':''}${b}`:`y＝${a}x ${b>=0?'＋':''}${b}`}</text><text class="fraction-answer" x="310" y="274">${quad?`頂點 (0, ${b})；${a>0?'開口向上':'開口向下'}`:`x 每增加 1，y ${a>0?'增加':'減少'} ${Math.abs(a)}`}</text>`;q('[data-coordinate-result]',lab).textContent=quad?`a 決定開口方向與寬窄；k＝${b} 把頂點上下移到 (0, ${b})。`:`斜率是 ${a}、截距是 ${b}；點 (0, ${b}) 一定在這條直線上。`;}
  function geometryLab(title){const root=title==='平方根',circle=title==='圓',trig=['三角比','生活測量'].includes(title);return `<div class="interactive-visual geometry-lab" data-geometry-lab data-geometry-title="${esc(title)}"><div class="visual-instruction">拖曳數值；圖形比例、面積與計算式同步改變。</div><div class="fraction-controls"><label>${circle?'半徑':'底邊'} <input type="range" min="2" max="10" value="${root?7:6}" data-geometry-a><output data-geometry-a-out></output></label><label>${circle?'圓心角':'高'} <input type="range" min="${circle?30:2}" max="${circle?180:10}" value="${circle?90:8}" step="${circle?30:1}" data-geometry-b><output data-geometry-b-out></output></label></div><svg class="fraction-svg" data-geometry-svg viewBox="0 0 620 255" role="img" aria-label="可調整幾何圖形模型"></svg><div class="fraction-result" data-geometry-result></div></div>`;}
  function renderGeometry(lab){const title=lab.dataset.geometryTitle,a=Number(q('[data-geometry-a]',lab).value),b=Number(q('[data-geometry-b]',lab).value),svg=q('[data-geometry-svg]',lab),root=title==='平方根',circle=title==='圓';q('[data-geometry-a-out]',lab).textContent=a;q('[data-geometry-b-out]',lab).textContent=b;if(root){svg.innerHTML=`<rect class="fraction-overlap" x="${310-a*9}" y="${130-a*9}" width="${a*18}" height="${a*18}"/><text class="fraction-title" x="310" y="30">面積 ${a*a} 的正方形</text><text class="fraction-answer" x="310" y="235">√${a*a} ＝ ${a}</text>`;q('[data-geometry-result]',lab).textContent=`邊長 ${a} 的正方形面積是 ${a*a}；平方根是在問「哪個非負邊長平方後會得到這個面積」。`;}else if(circle){const r=a,angle=b,endX=310+r*12*Math.cos(-Math.PI/2+angle*Math.PI/180),endY=130+r*12*Math.sin(-Math.PI/2+angle*Math.PI/180);svg.innerHTML=`<circle class="fraction-empty" cx="310" cy="130" r="${r*12}"/><path class="fraction-overlap" d="M310 130 L310 ${130-r*12} A${r*12} ${r*12} 0 0 1 ${endX} ${endY}Z"/><text class="fraction-title" x="310" y="24">半徑 ${r}；圓心角 ${angle}°</text><text class="fraction-answer" x="310" y="240">圓周角＝${angle/2}°（同弧）</text>`;q('[data-geometry-result]',lab).textContent=`同一段弧所對的圓周角是圓心角的一半：${angle}° ÷ 2 ＝ ${angle/2}°。`;}else{const scale=22,x=150,y=205,h=b*scale,w=a*scale,hyp=Math.sqrt(a*a+b*b).toFixed(1);svg.innerHTML=`<path class="fraction-vertical" d="M${x} ${y}H${x+w}V${y-h}Z"/><text x="${x+w/2}" y="${y+22}">${a}</text><text x="${x+w+18}" y="${y-h/2}">${b}</text><text class="fraction-title" x="310" y="28">直角三角形</text><text class="fraction-answer" x="310" y="242">斜邊＝√(${a}²＋${b}²) ≈ ${hyp}</text>`;q('[data-geometry-result]',lab).textContent=title==='畢氏定理'?`兩股平方和：${a*a}＋${b*b}＝${a*a+b*b}，所以斜邊約為 ${hyp}。`:`先把情境畫成直角三角形；可用對邊、鄰邊與斜邊的比例求未知量。`;}}
  function dataLab(title){const probability=title.includes('機率');return `<div class="interactive-visual data-lab" data-data-lab data-data-probability="${probability}"><div class="visual-instruction">${probability?'調整有利結果與全部結果；圓盤的有色比例就是機率。':'調整四筆資料；長條圖、平均數與中位數會同步改變。'}</div><div class="fraction-controls"><label>${probability?'有利結果':'資料 1'} <input type="range" min="1" max="10" value="${probability?3:4}" data-data-a><output data-data-a-out></output></label><label>${probability?'全部結果':'資料 2'} <input type="range" min="${probability?2:1}" max="10" value="${probability?8:8}" data-data-b><output data-data-b-out></output></label></div><svg class="fraction-svg" data-data-svg viewBox="0 0 620 230" role="img" aria-label="可調整統計資料與機率模型"></svg><div class="fraction-result" data-data-result></div></div>`;}
  function renderData(lab){let a=Number(q('[data-data-a]',lab).value),b=Number(q('[data-data-b]',lab).value),prob=lab.dataset.dataProbability==='true';if(prob)b=Math.max(a,b);q('[data-data-b]',lab).value=b;q('[data-data-a-out]',lab).textContent=a;q('[data-data-b-out]',lab).textContent=b;const svg=q('[data-data-svg]',lab);if(prob){const angle=a/b*360,endX=310+78*Math.cos(-Math.PI/2+angle*Math.PI/180),endY=115+78*Math.sin(-Math.PI/2+angle*Math.PI/180);svg.innerHTML=`<circle class="fraction-empty" cx="310" cy="115" r="78"/><path class="fraction-overlap" d="M310 115 L310 37 A78 78 0 ${angle>180?1:0} 1 ${endX} ${endY}Z"/><text class="fraction-title" x="310" y="30">有利 ${a} ／ 全部 ${b}</text><text class="fraction-answer" x="310" y="220">P＝${a}/${b}＝${(a/b).toFixed(2)}</text>`;q('[data-data-result]',lab).textContent=`把所有等可能結果切成 ${b} 份，其中 ${a} 份符合條件，所以機率是 ${a}/${b}。`;}else{const values=[a,b,6,9],mean=values.reduce((s,v)=>s+v,0)/4,sorted=[...values].sort((x,y)=>x-y),median=(sorted[1]+sorted[2])/2,bars=values.map((v,i)=>`<rect class="${i===0?'fraction-overlap':'fraction-vertical'}" x="${110+i*95}" y="${180-v*12}" width="55" height="${v*12}" rx="7"/><text x="${138+i*95}" y="${198}">${v}</text>`).join('');svg.innerHTML=`<text class="fraction-title" x="310" y="30">四筆資料的高度</text>${bars}<path d="M70 ${180-mean*12}H530" stroke="#e18434" stroke-width="4" stroke-dasharray="7 5"/><text class="fraction-answer" x="310" y="220">平均 ${mean.toFixed(1)}　｜　中位數 ${median}</text>`;q('[data-data-result]',lab).textContent=`排序後是 ${sorted.join('、')}；中間兩筆平均為 ${median}。虛線是總和平均分配後的平均數 ${mean.toFixed(1)}。`;}}
  function bodySystemLab(title){const digestive=title==='動物如何獲得養分',configs={
    '食物中的養分':['養分','能量','建構','調節'],'酵素與消化':['受質','酵素','分解','吸收'],'動物如何獲得養分':['食物','消化管','小分子','血液'],'植物的運輸構造':['水分','木質部','葉','蒸散'],'神經系統與反應':['刺激','受器','中樞','反應'],'內分泌與恆定':['偏離','激素','器官','回穩'],'體溫與水分恆定':['體溫','調節中樞','流汗／血管','回穩'],'生殖的基礎':['配子','受精','胚胎','新個體'],'遺傳與基因':['親代','配子','組合','性狀'],'演化與分類':['變異','環境篩選','繁殖','族群改變'],'生態系與能量流動':['植物','消費者','分解者','物質循環'],'神經與恆定':['刺激','受器','調節','恆定'],'遺傳與演化':['變異','遺傳','選擇','演化']}[title]||['輸入','運輸','調節','結果'];return `<div class="interactive-visual body-system-lab" data-body-system-lab data-body-title="${esc(title)}"><div class="visual-instruction">調整輸入量，觀察每個環節能通過多少，以及哪一段成為限制。</div><div class="fraction-controls"><label>輸入 <input type="range" min="0" max="10" value="8" data-body-input><output data-body-input-out></output></label><label>處理能力 <input type="range" min="0" max="10" value="6" data-body-capacity><output data-body-capacity-out></output></label></div>${digestive?'<figure class="system-reference-figure"><img src="assets/digestive-system-cc0.png" alt="公開授權的人體消化系統教材圖"><figcaption>先對照真正的消化系統構造，再用下方箭頭追蹤食物、消化後的小分子與血液運輸。<small>教材圖：Wikimedia Commons，CC0。</small></figcaption></figure>':''}<svg class="fraction-svg" data-body-svg viewBox="0 0 620 230" role="img" aria-label="可調整生物系統流程模型"></svg><div class="fraction-result" data-body-result></div></div>`;}
  function renderBodySystem(lab){const title=lab.dataset.bodyTitle,input=Number(q('[data-body-input]',lab).value),capacity=Number(q('[data-body-capacity]',lab).value),flow=Math.min(input,capacity),labels=({'食物中的養分':['養分','能量','建構','調節'],'酵素與消化':['受質','酵素','分解','吸收'],'動物如何獲得養分':['食物','消化管','小分子','血液'],'植物的運輸構造':['水分','木質部','葉','蒸散'],'神經系統與反應':['刺激','受器','中樞','反應'],'內分泌與恆定':['偏離','激素','器官','回穩'],'體溫與水分恆定':['體溫','調節中樞','流汗／血管','回穩'],'生殖的基礎':['配子','受精','胚胎','新個體'],'遺傳與基因':['親代','配子','組合','性狀'],'演化與分類':['變異','環境篩選','繁殖','族群改變'],'生態系與能量流動':['植物','消費者','分解者','物質循環'],'神經與恆定':['刺激','受器','調節','恆定'],'遺傳與演化':['變異','遺傳','選擇','演化']})[title]||['輸入','運輸','調節','結果'];q('[data-body-input-out]',lab).textContent=input;q('[data-body-capacity-out]',lab).textContent=capacity;const boxes=labels.map((label,i)=>`<rect class="${i===2&&capacity<input?'fraction-horizontal':'fraction-overlap'}" x="${55+i*140}" y="78" width="100" height="60" rx="12"/><text x="${105+i*140}" y="113">${label}</text>${i<3?`<path d="M${155+i*140} 108h34" stroke="#f05a22" stroke-width="${5+flow/2}" marker-end="url(#body-arrow)"/>`:''}`).join(''),svg=q('[data-body-svg]',lab);svg.innerHTML=`<defs><marker id="body-arrow" markerWidth="10" markerHeight="10" refX="8" refY="4" orient="auto"><path d="M0,0 L0,8 L9,4 z" fill="#f05a22"/></marker></defs><text class="fraction-title" x="310" y="30">${title}｜可通過量 ${flow}/10</text>${boxes}<text class="fraction-answer" x="310" y="210">${capacity<input?'處理能力不足，這一段限制結果。':'處理能力足夠，輸入量決定結果。'}</text>`;q('[data-body-result]',lab).textContent=`輸入 ${input}、處理能力 ${capacity}，實際能完成 ${flow}；請用本節名詞說出哪個環節限制了結果。`;}
  const gcd=(a,b)=>b?gcd(b,a%b):a;
  const lcm=(a,b)=>a*b/gcd(a,b);
  function fractionLab(title){
    const adding=title==='分數的加減';
    const a=adding?1:2,b=adding?3:3,c=adding?1:3,d=adding?6:4;
    return `<div class="interactive-visual fraction-lab" data-fraction-lab data-fraction-mode="${adding?'add':'multiply'}"><div class="visual-instruction">${adding?'調整兩個分數：先把每一格切成相同大小，再把有色格合起來。':'調整兩個分數：左邊選直向比例、上方選橫向比例；重疊的格子就是「其中的其中」。'}</div><div class="fraction-controls"><label>第一個分數 <input type="range" min="1" max="6" value="${a}" data-fraction-a>／<input type="range" min="2" max="8" value="${b}" data-fraction-b><output data-fraction-left></output></label><label>第二個分數 <input type="range" min="1" max="6" value="${c}" data-fraction-c>／<input type="range" min="2" max="8" value="${d}" data-fraction-d><output data-fraction-right></output></label></div><svg class="fraction-svg" data-fraction-svg viewBox="0 0 620 265" role="img" aria-label="可調整分數的面積模型"></svg><div class="fraction-result" data-fraction-result></div></div>`;
  }
  function fractionValue(input){return Number(q(input).value);}
  function renderFraction(lab){
    const mode=lab.dataset.fractionMode,a=fractionValue('[data-fraction-a]',lab),b=Math.max(a,fractionValue('[data-fraction-b]',lab)),c=fractionValue('[data-fraction-c]',lab),d=Math.max(c,fractionValue('[data-fraction-d]',lab));
    q('[data-fraction-b]',lab).value=b;q('[data-fraction-d]',lab).value=d;q('[data-fraction-left]',lab).textContent=`${a}/${b}`;q('[data-fraction-right]',lab).textContent=`${c}/${d}`;
    const svg=q('[data-fraction-svg]',lab),result=q('[data-fraction-result]',lab);
    if(mode==='add'){
      const parts=lcm(b,d), first=a*(parts/b), second=c*(parts/d), total=first+second, divisor=gcd(total,parts);
      const cells=Array.from({length:parts},(_,i)=>{const x=28+i*(564/parts),fill=i<first?'fraction-first':i<total?'fraction-second':'fraction-empty';return `<rect class="${fill}" x="${x}" y="102" width="${564/parts-2}" height="72" rx="3"/>`;}).join('');
      svg.innerHTML=`<text class="fraction-title" x="310" y="30">先通分：每一條都切成 ${parts} 等份</text><text x="28" y="75" class="fraction-label">${a}/${b} ＝ ${first}/${parts}</text><text x="592" y="75" class="fraction-label fraction-right-label">${c}/${d} ＝ ${second}/${parts}</text>${cells}<text x="310" y="215" class="fraction-answer">有色格：${first} ＋ ${second} ＝ ${total} 格</text>`;
      result.textContent=`${a}/${b} ＋ ${c}/${d} ＝ ${total}/${parts} ＝ ${total/divisor}/${parts/divisor}。兩個原本大小不同的分母，已經被改成相同大小的 ${parts} 等份，才能相加。`;
    } else {
      const divisor=gcd(a*c,b*d), rows=d,cols=b,cellW=360/cols,cellH=150/rows;
      const cells=Array.from({length:rows*cols},(_,i)=>{const row=Math.floor(i/cols),col=i%cols,vertical=col<a,horizontal=row<c,cls=vertical&&horizontal?'fraction-overlap':vertical?'fraction-vertical':horizontal?'fraction-horizontal':'fraction-empty';return `<rect class="${cls}" x="${130+col*cellW}" y="${58+row*cellH}" width="${cellW-2}" height="${cellH-2}" rx="2"/>`;}).join('');
      svg.innerHTML=`<text class="fraction-title" x="310" y="27">直向 ${a}/${b} × 橫向 ${c}/${d}</text><text x="308" y="248" class="fraction-answer">重疊 ${a*c} 格 ／ 全部 ${b*d} 格</text><text x="93" y="124" class="fraction-side-label">${c}/${d}</text><text x="310" y="48" class="fraction-top-label">${a}/${b}</text>${cells}`;
      result.textContent=`${a}/${b} × ${c}/${d} ＝ ${a*c}/${b*d} ＝ ${a*c/divisor}/${b*d/divisor}。紫色重疊區同時屬於兩個有色部分，所以它代表「${a}/${b} 的 ${c}/${d}」。`;
    }
  }
  const scienceScenario=title=>({
    '探究自然的方法':['experiment','操作變因','重複次數'], '基本測量':['measure','真實長度','尺的起點誤差'], '物質與密度':['density','質量 g','體積 cm³'],
    '化學反應':['reaction','反應物粒子','可配對粒子'], '酸鹼與指示劑':['ph','pH 值','指示劑'], '酸鹼鹽':['neutral','酸粒子','鹼粒子'], '化學反應速率':['rate','溫度','催化程度'],
    '聲音與波動':['wave','振幅','頻率'], '光與色彩':['light','紅光','綠光'], '溫度與熱':['heat','加熱時間','物質量'], '力與運動':['motion','推力','質量'], '壓力、浮力與機械':['pressure','受力','接觸面積'],
    '電與能量':['circuit','電池數','電阻'], '電流與磁場':['magnet','電流大小','線圈數'], '能源轉換':['energy','輸入能量','損失能量'], '板塊與地質':['plate','板塊推擠','地層阻力'], '天文與永續':['orbit','地球位置','自轉角度']
  }[title]||['experiment','操作變因','重複次數']);
  function scienceLab(title){const [mode,a,b]=scienceScenario(title),oneControl=mode==='ph',controls=`<label>${a} <input type="range" min="0" max="${oneControl?14:10}" value="${oneControl?7:7}" data-science-input><output data-science-input-out></output></label>${oneControl?'':`<label>${b} <input type="range" min="0" max="10" value="3" data-science-limit><output data-science-limit-out></output></label>`}`;return `<div class="interactive-visual science-lab" data-science-lab data-science-title="${esc(title)}"><div class="visual-instruction">調整「${a}」${oneControl?'':'與「'+b+'」'}；圖中的結構、箭頭與量測結果會依本節原理同步改變。</div><div class="fraction-controls">${controls}</div><svg class="fraction-svg" data-science-svg viewBox="0 0 620 220" role="img" aria-label="可操作的自然科概念模型"></svg><div class="fraction-result" data-science-result></div></div>`;}
  function renderScience(lab){const a=Number(q('[data-science-input]',lab).value),limitInput=q('[data-science-limit]',lab),b=limitInput?Number(limitInput.value):0,title=lab.dataset.scienceTitle,[mode,labelA,labelB]=scienceScenario(title),svg=q('[data-science-svg]',lab);q('[data-science-input-out]',lab).textContent=a;if(limitInput)q('[data-science-limit-out]',lab).textContent=b;let drawing='',result='';
    if(mode==='density'){const volume=Math.max(1,b),density=(a/volume).toFixed(2);drawing=`<rect class="fraction-overlap" x="130" y="${170-volume*10}" width="130" height="${volume*10}"/><rect class="fraction-vertical" x="375" y="${170-a*9}" width="90" height="${a*9}"/><text x="195" y="195">體積 ${volume} cm³</text><text x="420" y="195">質量 ${a} g</text><path d="M270 105h75" stroke="#486783" stroke-width="5"/><text class="fraction-answer" x="310" y="30">密度＝質量／體積＝${a}／${volume}＝${density}</text>`;result=`同樣體積時，質量越大密度越大；本次是 ${density} g/cm³。`}
    else if(mode==='ph'||mode==='neutral'){const ph=mode==='ph'?a:Math.max(0,Math.min(14,7+(b-a)));const color=ph<7?'#e96b7a':ph>7?'#5baee3':'#8e78d6';drawing=`<defs><linearGradient id="phscale"><stop stop-color="#e96b7a"/><stop offset=".5" stop-color="#8e78d6"/><stop offset="1" stop-color="#5baee3"/></linearGradient></defs><rect x="70" y="102" width="480" height="28" rx="14" fill="url(#phscale)"/><circle class="fraction-overlap" cx="${70+ph/14*480}" cy="116" r="17"/><text x="70" y="82">酸性 0</text><text x="310" y="82">中性 7</text><text x="550" y="82">鹼性 14</text><path d="M220 174h${mode==='neutral'?Math.min(a,b)*16:0}" stroke="#e18434" stroke-width="12"/><text class="fraction-answer" x="310" y="205">pH ${ph}${ph===7?'：酸、鹼剛好中和':ph<7?'：酸性':'：鹼性'}</text>`;result=mode==='neutral'?`可配對的酸、鹼粒子是 ${Math.min(a,b)} 組；剩下的粒子決定溶液偏酸或偏鹼。`:`pH ${ph} 的指示劑顏色會落在${ph<7?'紅黃端':'藍紫端'}；pH 是尺度，不是「酸的量」。`}
    else if(mode==='wave'){const amp=18+a*5,period=45+Math.max(1,10-b)*15,path=Array.from({length:80},(_,i)=>`${i?'L':'M'}${80+i*6} ${110+Math.sin(i*6/period*Math.PI*2)*amp}`).join('');drawing=`<path d="${path}" fill="none" stroke="#5baee3" stroke-width="5"/><path d="M75 110H555" stroke="#a8b8c8"/><text class="fraction-answer" x="310" y="205">振幅 ${amp}：音量；每秒振動 ${b}：音調</text>`;result='振幅變大是聲音更響；頻率變高是音調更高，兩者不可混為一談。'}
    else if(mode==='light'){const r=a*25,g=b*25,color=`rgb(${r},${g},70)`;drawing=`<circle cx="215" cy="110" r="68" fill="rgba(255,80,80,.42)"/><circle cx="335" cy="110" r="68" fill="rgba(80,255,120,.42)"/><circle class="fraction-overlap" cx="275" cy="110" r="38" fill="${color}"/><text class="fraction-answer" x="310" y="205">紅光 ${a} ＋ 綠光 ${b} → 疊加色</text>`;result='光的混色是加法：光越多越接近白；不是把顏料混在一起的減法。'}
    else if(mode==='heat'){const temp=20+a*5-b*2;drawing=`<path d="M260 55v95a50 50 0 1 0 100 0V55a50 50 0 0 0-100 0" fill="none" stroke="#486783" stroke-width="6"/><rect class="fraction-overlap" x="284" y="${175-Math.max(0,temp-20)*2}" width="52" height="${Math.max(0,temp-20)*2}" rx="24"/><text class="fraction-answer" x="310" y="205">溫度約 ${temp}°C</text>`;result='加熱時間提供能量；物質量越多，同樣能量造成的溫度變化越小。'}
    else if(mode==='motion'||mode==='pressure'){const value=mode==='motion'?(a/Math.max(1,b)).toFixed(2):(a/Math.max(1,b)).toFixed(2),width=mode==='motion'?80+a*16:Math.max(35,b*24);drawing=`<rect class="fraction-vertical" x="280" y="120" width="${width}" height="48" rx="8"/><path d="M80 144h${a*18}" stroke="#e18434" stroke-width="8"/><text x="120" y="125">${mode==='motion'?'推力':'受力'} ${a}</text><text class="fraction-answer" x="310" y="205">${mode==='motion'?'加速度＝推力／質量':'壓力＝受力／面積'}＝${value}</text>`;result=mode==='motion'?'相同推力下，質量越大越不容易改變運動狀態。':'同樣受力下，接觸面積越小，壓力越大。'}
    else if(mode==='circuit'||mode==='magnet'){const strength=mode==='circuit'?a/Math.max(1,b):a*b;drawing=`<path d="M120 120h105v-50h120v50h105v55H120z" fill="none" stroke="#486783" stroke-width="6"/><rect class="fraction-overlap" x="265" y="50" width="40" height="40"/><circle class="fraction-vertical" cx="175" cy="148" r="25"/><path d="M${225} 120h${Math.min(170,strength*14)}" stroke="#e18434" stroke-width="${3+Math.min(12,strength)}"/><text class="fraction-answer" x="310" y="205">${mode==='circuit'?'電流強度':'磁場強度'} ${Number(strength).toFixed(1)}</text>`;result=mode==='circuit'?'電池提高推動電荷的能力；電阻越大，電流越小。':'電流與線圈數增加，都會讓電磁鐵的磁場變強。'}
    else if(mode==='plate'||mode==='orbit'){const gap=mode==='plate'?Math.max(18,170-a*12):100+a*9;drawing=mode==='plate'?`<path class="fraction-vertical" d="M80 155h180l-35-55-45 28-42-28z"/><path class="fraction-horizontal" d="M540 155H360l35-55 45 28 42-28z"/><path d="M270 105h${gap-20}" stroke="#e18434" stroke-width="8" marker-end="url(#integer-arrow)"/><text class="fraction-answer" x="310" y="205">推擠 ${a}；地層阻力 ${b}</text>`:`<circle class="fraction-overlap" cx="310" cy="110" r="35"/><ellipse cx="310" cy="110" rx="${gap}" ry="60" fill="none" stroke="#486783" stroke-width="5"/><circle class="fraction-vertical" cx="${310+gap}" cy="110" r="13"/><text class="fraction-answer" x="310" y="205">地球在軌道位置 ${a}；日照角 ${b}</text>`;result=mode==='plate'?'板塊相對運動使地層累積應力；超過岩層承受能力才可能釋放成地震。':'地球繞日公轉與地軸傾斜改變日照角度，是四季的重要原因。'}
    else {const output=Math.max(0,a-b);drawing=`<circle cx="140" cy="112" r="38" fill="#1677c8" stroke="#084d89" stroke-width="4"/><path d="M190 112h220" stroke="#f05a22" stroke-width="${5+output}" marker-end="url(#science-arrow)"/><circle cx="455" cy="112" r="${18+output*4}" fill="#ffc438" stroke="#a75b00" stroke-width="4"/><text x="140" y="118" fill="#fff">${labelA}</text><text x="455" y="118">量測結果</text><text class="fraction-answer" x="310" y="205">可觀察差異 ${output}</text>`;result=`改變 ${labelA} 時，要固定其他條件並重複量測；${labelB} 會影響結果的可信度。`}
    svg.innerHTML=`<defs><marker id="science-arrow" markerWidth="10" markerHeight="10" refX="8" refY="4" orient="auto"><path d="M0,0 L0,8 L9,4 z" fill="#f05a22"/></marker></defs><text class="fraction-title" x="310" y="28">${title}</text>${drawing}`;q('[data-science-result]',lab).textContent=result;}
  const englishScenarios={
    '自我介紹與人稱代名詞':['sentence',['I am Kevin.','She is my sister.','They are classmates.'],'人稱改變時，be 動詞也要一起改變。'], '名詞、冠詞與數量':['sentence',['a book','an apple','three books'],'先看單數／複數與第一個發音，不是只看字母。'], '地點與介系詞':['sentence',['on the desk','in the box','between A and B'],'把物品放進空間圖，再選介系詞。'], '問句與簡答':['sentence',['Do you play? — Yes, I do.','Does Amy play? — Yes, she does.','Where does he live?'],'助動詞出現後，主要動詞要回原形。'], '比較級與最高級':['sentence',['taller than Tom','the tallest in class','more useful than this'],'比較要有對象；最高級通常在範圍中選一個。'], '比較級':['sentence',['fast → faster','happy → happier','beautiful → more beautiful'],'先看字尾變化與音節，再接 than。'], '情態助動詞':['sentence',['can swim','must wear a helmet','should study tonight'],'情態助動詞後面一律接原形動詞。'], '不定詞與動名詞':['sentence',['want to go','enjoy reading','stop to rest'],'先看前一個動詞的搭配，不能只翻中文。'], '連接詞':['sentence',['because it rained','but he stayed','so we went home'],'連接詞決定前後句的因果、轉折或結果。'], '被動語態入門':['sentence',['The cake is made.','The window was broken.','The homework will be checked.'],'被動＝be 動詞＋過去分詞；時態放在 be。'], '被動語態':['sentence',['is written by Amy','was built in 1990','will be sent tomorrow'],'先找接受動作的人，再選正確的 be 時態。'], '關係子句':['sentence',['the boy who runs','the book which I bought','the place where we met'],'先行詞是人、物或地點，決定關係詞。'], '分詞與長句':['sentence',['The girl wearing red','a broken window','Students invited yesterday'],'先抓主要主詞＋動詞，分詞是補充資訊。'],
    '日常作息與現在簡單式':['timeline',['every day','now','tomorrow'],['walks to school','is walking','will walk'],'習慣用現在簡單式，第三人稱單數動詞要加 s。'], '正在發生與現在進行式':['timeline',['usually','right now','next week'],['plays','is playing','will play'],'正在發生＝be＋V-ing，不只靠看到 now。'], '過去式與時間線':['timeline',['yesterday','today','next Saturday'],['visited','visits','will visit'],'先在時間線定位事件，再選動詞形式。'], '過去式':['timeline',['last night','these days','next month'],['studied','studies','will study'],'已結束的過去事件才用 V-ed／不規則過去式。'], '未來計畫與 be going to':['timeline',['already finished','planned this weekend','happening now'],['has finished','is going to travel','is travelling'],'be going to 常用於已有計畫或明顯徵兆。'], '未來式':['timeline',['last year','now','later'],['went','goes','will go'],'will＋原形動詞；未來時間不把 will 接在子句每個動詞前。'], '現在完成式':['timeline',['in the past','up to now','a future plan'],['went','has lived','will live'],'現在完成式把過去經驗或持續狀態連到現在。'],
    '生活情境閱讀':['reading',['公告：10:00 開放','限制：members only','答案：非會員不可進入'],'先圈人物、時間與限制詞。'], '短文寫作':['reading',['任務：介紹一次旅行','必寫：時間與感受','檢查：是否回應所有任務'],'寫作先完成任務點，再檢查句子。'], '閱讀圖表':['reading',['題目：找最多人選項','圖例：藍色＝星期一','答案：比較同一刻度'],'先確認圖例和單位，再讀數字。'], '情境對話':['reading',['情境：朋友遲到','語氣：道歉','合適回應：No problem.'],'先判斷說話目的，不是逐字翻譯。'], '段落寫作':['reading',['主題句：我的環保習慣','細節：自備水瓶','收束：減少塑膠垃圾'],'段落要有中心、具體細節與連接。'], '篇章連接':['reading',['前句：下雨','連接詞：however','後句：仍照常出發'],'however 表轉折，therefore 表結果。'], '推論閱讀':['reading',['線索：地上濕、大家拿傘','可推：剛下過雨','不可推：明天一定下雨'],'推論只能走到文本允許的位置。'], '圖表與公告':['reading',['公告：週二截止','限制：except Grade 9','答案：九年級不適用'],'公告題的關鍵是時間、對象與否定詞。'], '會考寫作':['reading',['任務：比較兩張圖片','段落一：描述差異','段落二：提出選擇與理由'],'先列任務清單，避免只寫漂亮卻漏答題目。']
  };
  function englishScenario(title,kind){return englishScenarios[title]||[kind,['線索 A','線索 B','線索 C'],'先以句子結構或文本證據驗證。'];}
  function englishLab(title,kind){const scenario=englishScenario(title,kind),labels=scenario[1];return `<div class="interactive-visual english-lab" data-english-lab data-english-kind="${scenario[0]}" data-english-title="${esc(title)}"><div class="visual-instruction">點選一種情境或結構；句子／時間線／證據卡會實際改寫，不是只換外框。</div><div class="visual-controls">${labels.map((label,i)=>`<button data-english-choice="${i}" class="${i===0?'is-active':''}">${esc(label)}</button>`).join('')}</div><svg class="fraction-svg" data-english-svg viewBox="0 0 620 210" role="img" aria-label="可操作的英文情境與句型模型"></svg><div class="fraction-result" data-english-result></div></div>`;}
  function renderEnglish(lab,index=0){const title=lab.dataset.englishTitle,[kind,items,third,fourth]=englishScenario(title,lab.dataset.englishKind),note=kind==='timeline'?fourth:third,svg=q('[data-english-svg]',lab),safe=index%items.length;if(kind==='timeline'){const forms=third,xs=[150,310,470];svg.innerHTML=`<path d="M100 112H520" stroke="#486783" stroke-width="5"/>${items.map((word,i)=>`<circle class="${i===safe?'fraction-overlap':'fraction-empty'}" cx="${xs[i]}" cy="112" r="24"/><text x="${xs[i]}" y="72">${word}</text><text x="${xs[i]}" y="160">${forms[i]}</text>`).join('')}<text class="fraction-title" x="310" y="28">${title}</text>`;q('[data-english-result]',lab).textContent=`${items[safe]} → ${forms[safe]}。${note}`;}else if(kind==='reading'){svg.innerHTML=`${items.map((item,i)=>`<rect class="${i===safe?'fraction-overlap':'fraction-empty'}" x="${70+i*180}" y="76" width="160" height="64" rx="10"/><text x="${150+i*180}" y="108">${item}</text>${i<2?`<path d="M${230+i*180} 108h20" stroke="#486783" stroke-width="${i<safe?7:3}"/>`:''}`).join('')}<text class="fraction-title" x="310" y="30">${title}</text>`;q('[data-english-result]',lab).textContent=`目前聚焦：「${items[safe]}」。${note}`;}else{const parts=items[safe].split(' '),first=parts.shift(),rest=parts.join(' ');svg.innerHTML=`<rect class="fraction-overlap" x="85" y="78" width="145" height="58" rx="10"/><text x="158" y="114">${first}</text><text x="280" y="114">＋</text><rect class="fraction-vertical" x="335" y="78" width="195" height="58" rx="10"/><text x="432" y="114">${rest}</text><text class="fraction-title" x="310" y="30">${title}</text><text class="fraction-answer" x="310" y="185">${items[safe]}</text>`;q('[data-english-result]',lab).textContent=`「${items[safe]}」：${note}`;}}
  const chineseScenarios={
    '字音、字形與詞義':['形聲線索','詞性位置','放回句意'],'成語與詞語運用':['整體白話','使用情境','語意是否合'],'句型、語法與標點':['主幹句','修飾語','停頓與語氣'],'字詞與語法':['詞性角色','句中位置','語意功能'],'文言虛詞':['前後關係','虛詞功能','白話重組'],'國學常識':['作品線索','時代體裁','閱讀用途'],
    '修辭與表達效果':['修辭手法','畫面與語氣','表達效果'],'記敘文本閱讀':['人物事件','轉折細節','情感主旨'],'說明文本閱讀':['說明對象','分類因果','重點結論'],'議論文本閱讀':['作者主張','理由證據','論證是否足'],'文言文句意':['人物動作','省略轉折','白話句意'],'古典詩歌意象':['景物意象','動作聲音','情感氛圍'],'文化常識':['文本背景','文化線索','理解句意'],'跨文本與圖表':['資料來源','相同差異','可支持結論'],'寫作表達':['中心句','具體例子','回扣題旨'],'古典詩文':['人物動作','關鍵虛詞','白話重組'],'抒情文本':['生活畫面','感官詞句','情緒轉折'],'議論寫作':['立場主張','理由例證','回應反方'],'說明與圖表':['圖表單位','文字說明','整合結論'],'修辭應用':['修辭手法','語氣畫面','表達效果'],'跨文本比較':['文本 A','文本 B','比較結論'],'寫作組織':['段落功能','細節順序','前後銜接'],'閱讀推論':['直接線索','合理推論','不能超推'],'文言統整':['人物關係','實虛詞','完整句意'],'論證閱讀':['核心主張','可查證據','替代解釋'],'跨文本素養':['來源與時間','觀點差異','整合判斷'],'修辭與語氣':['用字語序','說話語氣','讀者感受'],'資料判讀':['單位樣本','圖文關係','證據界線'],'會考閱讀策略':['題幹任務','回原文找','排除無據項']
  };
  function chineseScenario(title,kind){return chineseScenarios[title]|| (kind==='word'?['字形詞性','前後語境','正確詞義']:['文本線索','前後關係','有據結論']);}
  function chineseLab(title,kind){const labels=chineseScenario(title,kind);return `<div class="interactive-visual chinese-lab" data-chinese-lab data-chinese-kind="${kind}" data-chinese-title="${esc(title)}"><div class="visual-instruction">點選本節真正要判讀的線索；箭頭會累積成「證據 → 解釋 → 結論」，不是只切換外框。</div><div class="visual-controls">${labels.map((label,i)=>`<button data-chinese-choice="${i}" class="${i===0?'is-active':''}">${label}</button>`).join('')}</div><svg class="fraction-svg" data-chinese-svg viewBox="0 0 620 210" role="img" aria-label="可操作的國文判讀證據模型"></svg><div class="fraction-result" data-chinese-result></div></div>`;}
  function renderChinese(lab,index=0){const title=lab.dataset.chineseTitle,labels=chineseScenario(title,lab.dataset.chineseKind),svg=q('[data-chinese-svg]',lab),safe=index%labels.length;svg.innerHTML=`<text class="fraction-title" x="310" y="30">${title}</text>${labels.map((x,i)=>`<rect class="${i===safe?'fraction-overlap':'fraction-empty'}" x="${70+i*180}" y="82" width="160" height="55" rx="10"/><text x="${150+i*180}" y="114">${x}</text>${i<2?`<path d="M${230+i*180} 109h20" stroke="#486783" stroke-width="${i<safe?7:3}"/>`:''}`).join('')}<text class="fraction-answer" x="310" y="184">${safe===0?'先抓可回查的詞句，不急著猜答案。':safe===1?'說明這個線索如何支持你的理解。':'結論必須能回指前面的文本證據。'}</text>`;q('[data-chinese-result]',lab).textContent=`目前走到「${labels[safe]}」。${safe===2?'請回頭檢查：前兩個節點真的能支持這個結論嗎？':'再點下一步，讓理解有依據地往前推。'}`;}
  const socialScenarios={
    '史前與原住民族':['考古與口傳','多元生活','族群理解'],'荷西與鄭氏時期':['海上貿易','政權治理','移民社會'],'清代臺灣的治理':['開墾移民','行政治理','社會結構'],'開港與近代化':['通商開港','商品人口流動','城市制度改變'],'近代臺灣與東亞':['區域局勢','地方制度','人民回應'],'中國近代變遷':['內部壓力','改革革命','社會轉型'],'世界近代史':['工業化','帝國與交流','區域影響'],'現代臺灣':['政治經濟轉型','社會運動','生活權利改變'],'世界現代史':['冷戰科技','全球連動','各地差異'],
    '地圖與地理資訊':['圖例與方向','比例尺位置','空間判讀'],'臺灣的位置與區域':['經緯與鄰海','交通交流','區位意義'],'人口與聚落':['地形水源','工作交通','人口分布'],'產業活動與區位':['原料勞力','交通市場','選址結果'],'資源與環境問題':['資源利用','環境代價','保育調適'],'中國與東亞地理':['自然條件','人口產業','區域比較'],'人口與產業':['資源交通','市場政策','發展差異'],'世界區域地理':['位置氣候','人文活動','區域特色'],'全球化與環境':['跨境流動','受益代價','環境回應'],'全球化與區域議題':['跨國連結','地方影響','合作取捨'],'永續發展':['環境保護','社會公平','經濟可行'],
    '社會生活與規範':['生活行為','規範種類','可能後果'],'人性尊嚴與權利':['個人權利','他人界線','公共利益'],'家庭與校園生活':['角色責任','溝通規則','共同生活'],'社區參與':['公共問題','參與程序','改善檢驗'],'政府與公共服務':['共同需求','資源程序','公共服務'],'媒體與資訊識讀':['來源時間','證據立場','交叉查證'],'法律與生活':['事實角色','權利義務','法律程序'],'政府與民主':['人民授權','權力制衡','權利保障'],'市場與金融':['需求供給','價格訊號','消費選擇'],'民主政治':['選舉參與','多數決策','少數保障'],'公共參與':['可查資料','提出理由','公共決策'],'法律與權利救濟':['權利受損','申訴救濟','公平處理'],'跨科公共議題':['自然證據','數學資料','制度取捨']
  };
  function socialScenario(title,kind){return socialScenarios[title]||(kind==='map'?['位置圖例','空間條件','人地影響']:kind==='timeline'?['背景條件','關鍵事件','後續影響']:['角色權利','規則程序','公共結果']);}
  function socialLab(title,kind){const labels=socialScenario(title,kind);return `<div class="interactive-visual social-lab" data-social-lab data-social-kind="${kind}" data-social-title="${esc(title)}"><div class="visual-instruction">逐步點選本節的背景、機制與影響；模型會建立因果鏈，不能只看名稱或年份。</div><div class="visual-controls">${labels.map((label,i)=>`<button data-social-choice="${i}" class="${i===0?'is-active':''}">${label}</button>`).join('')}</div><svg class="fraction-svg" data-social-svg viewBox="0 0 620 210" role="img" aria-label="可操作的社會科因果模型"></svg><div class="fraction-result" data-social-result></div></div>`;}
  function renderSocial(lab,index=0){const title=lab.dataset.socialTitle,labels=socialScenario(title,lab.dataset.socialKind),svg=q('[data-social-svg]',lab),safe=index%labels.length;svg.innerHTML=`<text class="fraction-title" x="310" y="30">${title}</text>${labels.map((x,i)=>`<circle class="${i===safe?'fraction-overlap':'fraction-empty'}" cx="${130+i*180}" cy="110" r="38"/><text x="${130+i*180}" y="116">${x}</text>${i<2?`<path d="M${168+i*180} 110h104" stroke="#486783" stroke-width="${i<safe?8:3}" marker-end="url(#integer-arrow)"/>`:''}`).join('')}<text class="fraction-answer" x="310" y="190">${safe===0?'先定位條件與角色。':safe===1?'說明它怎麼改變原本條件。':'把影響連回誰、何時、何地與制度。'}</text>`;q('[data-social-result]',lab).textContent=`已選「${labels[safe]}」：${safe===2?'請用「因為…所以…造成…」完整說明。':'再點下一節點，避免把單一名詞當作答案。'}`;}
  function balanceLab(title){return `<div class="interactive-visual balance-lab" data-balance-lab data-balance-title="${esc(title)}"><div class="visual-instruction">調整 x；兩邊的重量會改變，找出天平剛好平衡的位置。</div><div class="fraction-controls"><label>x <input type="range" min="-5" max="10" value="5" data-balance-x><output data-balance-x-out></output></label></div><svg class="fraction-svg" data-balance-svg viewBox="0 0 620 220" role="img" aria-label="可調整方程式天平"></svg><div class="fraction-result" data-balance-result></div></div>`;}
  function renderBalance(lab){const x=Number(q('[data-balance-x]',lab).value),left=3*x-5,right=10,delta=left-right,angle=Math.max(-10,Math.min(10,delta*2)),svg=q('[data-balance-svg]',lab);q('[data-balance-x-out]',lab).textContent=x;svg.innerHTML=`<text class="fraction-title" x="310" y="28">3x − 5 ＝ 10</text><path d="M130 ${130-angle}H490 ${130+angle}" stroke="#486783" stroke-width="8"/><path d="M310 130v48" stroke="#486783" stroke-width="8"/><rect class="fraction-vertical" x="145" y="${82-angle}" width="100" height="32" rx="8"/><rect class="fraction-overlap" x="375" y="${82+angle}" width="100" height="32" rx="8"/><text x="195" y="${104-angle}">${left}</text><text x="425" y="${104+angle}">${right}</text><text class="fraction-answer" x="310" y="210">${left===right?'平衡：x＝5':'尚未平衡'}</text>`;q('[data-balance-result]',lab).textContent=left===right?'3x−5＝10，兩邊同加 5 後 3x＝15，所以 x＝5。':`x＝${x} 時左邊 ${left}、右邊 ${right}；繼續調整直到兩邊相同。`;}
  const cellScenario=title=>({'生命現象與生物圈':['life','可用能量','廢物累積'],'細胞的構造':['structure','聚焦構造','細胞類型'],'物質進出細胞':['diffusion','細胞外濃度','細胞內濃度'],'生物體的組成層次':['levels','放大層次','同類細胞數']}[title]||['diffusion','細胞外濃度','細胞內濃度']);
  function cellLab(title){const [,a,b]=cellScenario(title),isStructure=title==='細胞的構造';return `<div class="interactive-visual cell-lab" data-cell-lab data-cell-title="${esc(title)}"><div class="visual-instruction">調整「${a}」與「${b}」；不要背名詞，直接看本節結構或物質如何改變。</div><div class="fraction-controls"><label>${a} <input type="range" min="0" max="10" value="8" data-cell-out><output data-cell-out-out></output></label><label>${b} <input type="range" min="0" max="10" value="${isStructure?6:3}" data-cell-in><output data-cell-in-out></output></label></div>${isStructure?`<figure class="cell-reference-figure" data-cell-reference><img data-cell-reference-image src="assets/plant-cell-pd.png" alt="公開領域植物細胞結構教材圖"><figcaption><b data-cell-reference-focus>植物細胞｜細胞核</b><span data-cell-reference-detail>細胞核保存遺傳訊息並協調細胞活動。</span><small>教材圖：Wikimedia Commons 公開領域圖，作者 LadyofHats。</small></figcaption></figure>`:''}<svg class="fraction-svg" data-cell-svg viewBox="0 0 620 220" role="img" aria-label="可操作的細胞與生命組成模型" ${isStructure?'hidden':''}></svg><div class="fraction-result" data-cell-result></div></div>`;}
  function renderCell(lab){const a=Number(q('[data-cell-out]',lab).value),b=Number(q('[data-cell-in]',lab).value),title=lab.dataset.cellTitle,[mode]=cellScenario(title),svg=q('[data-cell-svg]',lab);q('[data-cell-out-out]',lab).textContent=a;q('[data-cell-in-out]',lab).textContent=b;const dots=(n,x0,y0=70)=>Array.from({length:n},(_,i)=>`<circle class="fraction-vertical" cx="${x0+(i%5)*20}" cy="${y0+Math.floor(i/5)*22}" r="6"/>`).join('');let drawing='',result='';
    if(mode==='structure'){const focus=Math.min(3,Math.floor(a/3)),plant=b>=5,names=['細胞膜','細胞核','粒線體','葉綠體'],active=names[focus],detail=active==='細胞膜'?'選擇性控制物質進出細胞。':active==='細胞核'?'保存遺傳訊息並協調細胞活動。':active==='粒線體'?'進行呼吸作用，釋放細胞可用的能量。':'利用光合作用製造養分；只有植物細胞具有。',reference=q('[data-cell-reference]',lab);if(reference){const image=q('[data-cell-reference-image]',reference),focusText=q('[data-cell-reference-focus]',reference),detailText=q('[data-cell-reference-detail]',reference);image.src=plant?'assets/plant-cell-pd.png':'assets/animal-cell-pd.svg';image.alt=plant?'公開領域植物細胞結構教材圖':'公開領域動物細胞結構教材圖';reference.dataset.focus=String(focus);focusText.textContent=`${plant?'植物':'動物'}細胞｜${active}`;detailText.textContent=detail;}result=`現在使用公開領域的教材結構圖，而非簡化圓點圖。${plant?'植物細胞具有細胞壁、葉綠體與大型液泡。':'動物細胞沒有細胞壁與葉綠體。'} 滑動「聚焦構造」可逐一核對功能。`}
    else if(mode==='levels'){const index=Math.min(3,Math.floor(a/3)),items=['細胞','組織','器官','個體'],sizes=[26,48,72,96],x=130+index*125;drawing=`${items.map((name,i)=>`<circle class="${i===index?'fraction-overlap':'fraction-empty'}" cx="${130+i*125}" cy="110" r="${sizes[i]/2}"/><text x="${130+i*125}" y="115">${name}</text>${i<3?`<path d="M${157+i*125} 110h62" stroke="#486783" stroke-width="4"/>`:''}`).join('')}<text class="fraction-answer" x="310" y="205">目前放大到：${items[index]}</text>`;result=`${b} 個同類細胞先組成組織；不同組織協作才形成器官，再共同維持個體。`}
    else if(mode==='life'){const activity=Math.max(0,a-b),r=30+activity*5;drawing=`<circle class="fraction-empty" cx="310" cy="112" r="${r}"/><path d="M120 112h${110+activity*8}" stroke="#e18434" stroke-width="${4+activity}"/><path d="M${370+r} 112h${Math.max(20,100-b*6)}" stroke="#5baee3" stroke-width="${4+Math.max(0,b/2)}"/><text x="160" y="90">能量／養分</text><text x="465" y="90">廢物排出</text><text class="fraction-answer" x="310" y="205">可維持活動 ${activity}/10</text>`;result='生命現象不是單一特徵：細胞必須取得能量、排出廢物、對刺激反應並維持內部穩定。'}
    else {const flow=a-b,from=flow>=0?250:365,to=flow>=0?345:270;drawing=`${dots(a,72)}<ellipse class="fraction-empty" cx="405" cy="115" rx="115" ry="72"/>${dots(b,350)}<path d="M${from} 115H${to}" stroke="#e15c24" stroke-width="${5+Math.abs(flow)}" marker-end="url(#cell-flow-arrow)"/><text class="fraction-answer" x="310" y="210">${flow===0?'兩側平衡':flow>0?'粒子由外側高濃度 → 細胞內低濃度':'粒子由細胞內高濃度 → 外側低濃度'}</text>`;result=`外側 ${a}、內側 ${b}；粒子由濃度高處擴散到低處，直到動態平衡。`}
    if(mode!=='structure')svg.innerHTML=`<defs><marker id="cell-flow-arrow" markerWidth="10" markerHeight="10" refX="8" refY="4" orient="auto"><path d="M0,0 L0,8 L9,4 z" fill="#e15c24"/></marker></defs><text class="fraction-title" x="310" y="28">${title}</text>${drawing}`;q('[data-cell-result]',lab).textContent=result;}
  function inequalityLab(){return `<div class="interactive-visual inequality-lab" data-inequality-lab><div class="visual-instruction">調整臨界值與符號；數線上的端點與解集會同步改變。</div><div class="fraction-controls"><label>臨界值 <input type="range" min="-8" max="8" value="3" data-inequality-value><output data-inequality-out></output></label></div><div class="visual-controls"><button data-inequality-dir="less" class="is-active">x ＜／≤ k</button><button data-inequality-dir="greater">x ＞／≥ k</button></div><svg class="fraction-svg" data-inequality-svg viewBox="0 0 620 190" role="img" aria-label="可調整不等式數線"></svg><div class="fraction-result" data-inequality-result></div></div>`;}
  function renderInequality(lab){const value=Number(q('[data-inequality-value]',lab).value),dir=lab.dataset.inequalityDir||'less',x=310+value*28,left=dir==='less',svg=q('[data-inequality-svg]',lab);q('[data-inequality-out]',lab).textContent=value;svg.innerHTML=`<path d="M70 105H550" stroke="#486783" stroke-width="5"/>${Array.from({length:17},(_,i)=>{const n=i-8,px=310+n*28;return `<path d="M${px} 95v20" stroke="#486783"/><text x="${px}" y="150">${n}</text>`;}).join('')}<path d="M${x} 75H${left?75:545}" stroke="#e18434" stroke-width="10"/><circle class="fraction-overlap" cx="${x}" cy="105" r="12"/><text class="fraction-title" x="310" y="28">x ${left?'＜':'＞'} ${value}</text>`;q('[data-inequality-result]',lab).textContent=`端點 ${value} ${left?'左':'右'}側是解集；代入一個點驗算，例如 x＝${left?value-1:value+1}。`;}
  function replayLab(lab){
    const model=q('[data-model]',lab); model?.classList.remove('is-playing');
    if(lab._replayTimer) clearInterval(lab._replayTimer);
    requestAnimationFrame(()=>model?.classList.add('is-playing'));
    const absolute=q('[data-absolute-lab]',lab);
    if(absolute){const input=q('[data-absolute-slider]',absolute), values=[-4,0,5,-2], readout=q('[data-absolute-readout]',absolute);let step=0;const show=()=>{if(step>=values.length){clearInterval(lab._replayTimer);lab._replayTimer=null;return;}input.value=values[step];renderAbsolute(absolute);readout.textContent=`播放第 ${step+1} 步：${readout.textContent}`;step+=1;};show();lab._replayTimer=setInterval(show,850);return;}
    const integer=q('[data-integer-lab]',lab);
    if(integer){const start=q('[data-integer-start]',integer),change=q('[data-integer-change]',integer),values=[[-2,5],[3,-6],[-5,-3]];let step=0;const show=()=>{if(step>=values.length){clearInterval(lab._replayTimer);lab._replayTimer=null;return;}[start.value,change.value]=values[step];renderInteger(integer);q('[data-integer-readout]',integer).textContent=`播放第 ${step+1} 步：${q('[data-integer-readout]',integer).textContent}`;step+=1;};show();lab._replayTimer=setInterval(show,1000);return;}
    const concept=q('[data-concept-visual]',lab);
    if(concept){const options=[...concept.querySelectorAll('[data-concept-option]')];let step=0;const show=()=>{if(step>=options.length){clearInterval(lab._replayTimer);lab._replayTimer=null;return;}options.forEach((button,index)=>button.classList.toggle('is-active',index===step));q('[data-concept-diagram]',concept).dataset.step=String(step);q('[data-concept-status]',concept).textContent=`播放第 ${step+1} 步：${options[step].textContent}。`;step+=1;};show();lab._replayTimer=setInterval(show,850);return;}
    const visual=q('[data-visual]',lab);
    if(visual){
      const nodes=[...visual.querySelectorAll('[data-visual-node]')]; let step=0;
      nodes.forEach(node=>node.classList.remove('is-active'));
      const show=()=>{const node=nodes[step]; if(!node){clearInterval(lab._replayTimer);lab._replayTimer=null;return;}node.classList.add('is-active');q('[data-visual-status]',visual).textContent=`播放第 ${step+1} 步：${node.textContent.trim()}。`;step+=1;};
      show(); lab._replayTimer=setInterval(show,850); return;
    }
    const math=q('[data-math-visual]',lab);
    if(math){const buttons=[...math.querySelectorAll('[data-math-step]')];let step=0;const messages=['圈出已知條件。','把相同的量建立關係。','代回圖像驗證結果。'];const show=()=>{if(step>=buttons.length){clearInterval(lab._replayTimer);lab._replayTimer=null;return;}buttons.forEach((button,index)=>button.classList.toggle('is-active',index===step));q('[data-math-status]',math).textContent=`播放第 ${step+1} 步：${messages[step]}`;step+=1;};show();lab._replayTimer=setInterval(show,850);}
  }
  function taiwanEnvironmentLab(){
    return `<div class="interactive-visual taiwan-lab" data-taiwan-lab><div class="math-model-label">拖曳圖層：同一個地點，環境條件會改變人的選擇</div><div class="layer-controls" role="group" aria-label="臺灣環境圖層"><button class="is-active" data-taiwan-layer="terrain">地形</button><button data-taiwan-layer="climate">氣候</button><button data-taiwan-layer="hazard">災害風險</button></div><svg class="taiwan-map-svg" data-taiwan-map viewBox="0 0 380 310" role="img" aria-label="可切換地形、氣候與災害資訊的臺灣地圖"></svg><div class="visual-status" data-taiwan-status>地形圖層：中央山脈使東、西側的生活與交通條件不同。</div></div>`;
  }
  function renderTaiwanLab(lab,mode='terrain'){
    const svg=q('[data-taiwan-map]',lab), status=q('[data-taiwan-status]',lab);
    const layers={
      terrain:{title:'地形｜山脈與平原',paths:`<path class="tw-land tw-west" d="M154 39 121 98l7 70 22 74 37 39 17-88-17-91z"/><path class="tw-land tw-mountain" d="M173 42 205 102l17 91-17 88-18-42-22-74z"/><path class="tw-land tw-east" d="M205 102 232 111l14 54-20 72-21 42 17-88z"/>`,labels:`<text x="102" y="150">西部平原</text><text x="190" y="138">中央山脈</text><text x="268" y="180">東部</text>`,note:'地形圖層：中央山脈使東、西側的生活與交通條件不同。'},
      climate:{title:'氣候｜雨量與季風',paths:`<path class="tw-land tw-north-rain" d="M154 39 173 42 205 102 182 119 149 91z"/><path class="tw-land tw-east-rain" d="M205 102 232 111l14 54-20 72-21 42 17-88z"/><path class="tw-land tw-south-dry" d="M149 91 182 119l23 162-18 0-37-39-22-74z"/>`,labels:`<text x="125" y="74">冬季較濕</text><text x="273" y="154">迎風多雨</text><text x="117" y="231">南部較乾</text>`,note:'氣候圖層：季風、緯度與地形共同影響雨量；東側與北部常較濕。'},
      hazard:{title:'災害｜先看地形再判斷',paths:`<path class="tw-land tw-slope" d="M173 42 205 102l17 91-17 88-18-42-22-74z"/><path class="tw-land tw-flood" d="M154 39 173 42l9 77-33-28-21 77-7-70z"/><path class="tw-land tw-coast" d="M205 102 232 111l14 54-20 72-21 42 17-88z"/>`,labels:`<text x="188" y="144">坡地崩塌</text><text x="100" y="167">淹水</text><text x="275" y="194">颱風強風</text>`,note:'災害圖層：山區注意坡地災害；低窪平原注意淹水；沿海需面對颱風與強風。'}
    }[mode];
    svg.innerHTML=`<text class="tw-title" x="190" y="24">${layers.title}</text><path class="tw-outline" d="M154 39 173 42 205 102 232 111 246 165 226 237 205 281 187 281 150 242 128 168 121 98z"/>${layers.paths}${layers.labels}<circle class="tw-pin" cx="184" cy="172" r="8"/><text class="tw-hint" x="190" y="302">點選其他圖層，比較同一座島的不同資訊</text>`;
    status.textContent=layers.note;
  }
  function photosynthesisLab(){
    return `<div class="interactive-visual photosynthesis-lab" data-photo-lab><div class="math-model-label">調整原料：哪一種不足會卡住光合作用？</div><div class="photo-controls"><label>光 <input type="range" min="0" max="10" value="7" data-photo-light><output data-photo-light-out>7</output></label><label>水 <input type="range" min="0" max="10" value="5" data-photo-water><output data-photo-water-out>5</output></label><label>二氧化碳 <input type="range" min="0" max="10" value="8" data-photo-co2><output data-photo-co2-out>8</output></label></div><svg class="photo-svg" data-photo-svg viewBox="0 0 420 250" role="img" aria-label="可調整光、水與二氧化碳的光合作用模擬"></svg><div class="photo-result" data-photo-result></div></div>`;
  }
  function renderPhotosynthesisLab(lab){
    const light=Number(q('[data-photo-light]',lab).value),water=Number(q('[data-photo-water]',lab).value),co2=Number(q('[data-photo-co2]',lab).value),rate=Math.min(light,water,co2),limiting=[['光',light],['水',water],['二氧化碳',co2]].filter(([,value])=>value===rate).map(([name])=>name).join('、');
    q('[data-photo-light-out]',lab).textContent=light;q('[data-photo-water-out]',lab).textContent=water;q('[data-photo-co2-out]',lab).textContent=co2;
    const oxygen=Array.from({length:rate},(_,i)=>`<circle class="oxygen-bubble" cx="${292+(i%4)*20}" cy="${110-Math.floor(i/4)*22}" r="7"/>`).join('');
    const co2Dots=Array.from({length:co2},(_,i)=>`<circle class="co2-dot" cx="${26+(i%5)*18}" cy="${90+Math.floor(i/5)*18}" r="6"/>`).join('');
    const svg=q('[data-photo-svg]',lab);svg.innerHTML=`<circle class="photo-sun" cx="79" cy="54" r="${14+light*2}"/><text x="79" y="59">光</text>${co2Dots}<text x="54" y="170">CO₂</text><path class="water-flow" d="M205 232v-58" style="stroke-width:${4+water*1.8}"/><text x="205" y="246">水</text><path class="leaf" d="M190 167C195 60 325 59 326 161c-60 50-109 21-136 6z" style="filter:saturate(${.35+rate/10})"/><path class="leaf-vein" d="M202 162 291 96m-50 47 19-42m-52 65-1-43"/><text x="258" y="148">葉綠體</text><path class="photo-arrow" d="M108 78 185 119"/><path class="photo-arrow" d="M122 119 190 139"/><text x="290" y="55">氧氣</text>${oxygen}<rect class="sugar" x="268" y="180" width="${20+rate*6}" height="24" rx="7"/><text x="289" y="198">養分</text>`;
    q('[data-photo-result]',lab).textContent=`目前產量：${rate}/10。限制因子是「${limiting}」；即使其他原料很多，缺少它時養分與氧氣也無法再增加。`;
  }
  function conceptVisual(subject,kind,title,sequence){
    if(title==='臺灣的自然環境') return taiwanEnvironmentLab();
    if(title==='植物如何製造養分') return photosynthesisLab();
    const labels={cell:['細胞膜','細胞核','細胞質'],body:['輸入','運輸／調節','結果'],experiment:['改變的變因','保持不變','量測結果'],physics:['作用','方向','結果'],earth:['地球內部／板塊','相對運動','地表現象'],timeline:['過去','現在','未來／結果'],sentence:['主詞','動詞','補充資訊'],reading:['題目任務','文本線索','有據答案'],word:['字形／詞義','前後語境','正確用法'],text:['主張／中心','證據／詞句','判讀結果'],map:['位置','空間條件','人地影響'],civic:['角色','權利／規則','程序結果']};
    const parts=labels[kind]||['條件','關係','結果'];
    let diagram='';
    if(kind==='cell') diagram=`<svg class="concept-svg cell-svg" viewBox="0 0 380 210"><ellipse class="cell-membrane" cx="190" cy="105" rx="145" ry="78"/><circle class="cell-nucleus" cx="190" cy="105" r="35"/><circle class="cell-cytoplasm" cx="108" cy="72" r="12"/><circle class="cell-cytoplasm" cx="272" cy="140" r="12"/><text x="190" y="112">細胞核</text><text x="190" y="28">細胞膜</text><text x="260" y="188">細胞質</text></svg>`;
    else if(kind==='body'){
      if(title.includes('植物'))diagram=`<svg class="concept-svg body-svg" viewBox="0 0 380 210"><circle cx="70" cy="50" r="24"/><path class="process-line" d="M104 55h95m-40-15 40 15-40 15"/><path d="M230 172V68m0 38l-58-45m58 45l58-45m-58 15l-36 48m36-48l36 48"/><text x="70" y="55">光</text><text x="155" y="37">二氧化碳＋水</text><text x="230" y="68">葉</text><text x="310" y="120">養分＋氧氣</text></svg>`;
      else if(title.includes('血液'))diagram=`<svg class="concept-svg body-svg" viewBox="0 0 380 210"><path d="M188 158c-95-67-62-139 0-73 62-66 95 6 0 73z"/><path class="process-line" d="M52 104h95m-24-18 24 18-24 18M229 104h100m-24-18 24 18-24 18"/><text x="82" y="82">全身</text><text x="188" y="113">心臟</text><text x="300" y="82">肺部</text></svg>`;
      else if(title.includes('神經'))diagram=`<svg class="concept-svg body-svg" viewBox="0 0 380 210"><circle cx="70" cy="105" r="24"/><path d="M94 105h78m0 0l45-48m-45 48l45 48m0-96h105"/><circle cx="328" cy="105" r="23"/><text x="70" y="110">受器</text><text x="188" y="90">神經</text><text x="328" y="110">反應</text></svg>`;
      else if(title.includes('遺傳')||title.includes('演化'))diagram=`<div class="gene-grid"><b>親代</b><span>A</span><span>a</span><span>A</span><strong>AA</strong><strong>Aa</strong><span>a</span><strong>Aa</strong><strong>aa</strong></div>`;
      else if(title.includes('生態'))diagram=`<div class="food-web"><b>植物</b><i>→</i><b>昆蟲</b><i>→</i><b>鳥類</b><i>→</i><b>分解者</b></div>`;
      else diagram=`<svg class="concept-svg body-svg" viewBox="0 0 380 210"><circle cx="96" cy="40" r="20"/><path d="M96 60v72m-42-45h84m-42 45l-30 52m30-52l30 52"/><path class="process-line" d="M170 105h155"/><circle class="process-dot" cx="225" cy="105" r="20"/><text x="225" y="111">系統</text><text x="278" y="88">物質／訊息</text></svg>`;
    }
    else if(kind==='experiment') diagram=`<svg class="concept-svg experiment-svg" viewBox="0 0 380 210"><path d="M80 25v86l-30 50q0 22 60 22t60-22l-30-50V25"/><path d="M225 35v120m-28 0h56"/><rect x="258" y="72" width="82" height="58" rx="9"/><text x="110" y="205">操作條件</text><text x="298" y="106">量測</text></svg>`;
    else if(kind==='physics') diagram=`<svg class="concept-svg physics-svg" viewBox="0 0 380 210"><rect x="122" y="100" width="125" height="58" rx="8"/><path class="force-arrow" d="M46 129h74m-18-18l18 18-18 18M250 129h82m-18-18l18 18-18 18"/><text x="185" y="135">物體</text><text x="46" y="93">力／能量</text><text x="273" y="93">運動／變化</text></svg>`;
    else if(kind==='earth') diagram=`<svg class="concept-svg earth-svg" viewBox="0 0 380 210"><path d="M30 133l130-33 30 28 30-28 130 33v44H30z"/><path class="plate-arrow" d="M142 75h-58m15-15-15 15 15 15M238 75h58m-15-15 15 15-15 15"/><circle cx="190" cy="48" r="22"/><text x="190" y="53">板塊</text><text x="190" y="194">地震／火山／地形</text></svg>`;
    else if(kind==='timeline') diagram=`<svg class="concept-svg timeline-svg" viewBox="0 0 380 210"><path d="M34 120h310"/><circle class="time-past" cx="82" cy="120" r="17"/><circle class="time-now" cx="190" cy="120" r="17"/><circle class="time-result" cx="298" cy="120" r="17"/><text x="82" y="82">時間線索</text><text x="190" y="160">動詞／事件</text><text x="298" y="82">答案</text></svg>`;
    else if(kind==='sentence') diagram=`<div class="sentence-slots"><b data-slot="0">誰／什麼</b><i>＋</i><b data-slot="1">做什麼</b><i>＋</i><b data-slot="2">何時／哪裡</b><output data-sentence-output>先選一句中的主詞</output></div>`;
    else if(kind==='reading'||kind==='text') diagram=`<div class="evidence-board"><b data-evidence="0">題目要問什麼？</b><span data-evidence="1">找回原文的關鍵句</span><strong data-evidence="2">用證據選答案</strong></div>`;
    else if(kind==='word') diagram=`<div class="word-board"><b data-word="0">字形／詞性</b><i>＋</i><b data-word="1">前後句意</b><i>＝</i><strong data-word="2">詞義</strong></div>`;
    else if(kind==='map') diagram=`<svg class="concept-svg map-svg" viewBox="0 0 380 210"><path d="M165 25l50 20 32 58-24 78-63 8-31-50 13-70z"/><circle cx="183" cy="106" r="9"/><path class="map-route" d="M55 162l128-56 135-35"/><text x="183" y="203">位置、距離、環境</text></svg>`;
    else diagram=`<div class="civic-board"><b data-civic="0">人民／角色</b><i>→</i><b data-civic="1">權利與規則</b><i>→</i><strong data-civic="2">程序與結果</strong></div>`;
    return `<div class="interactive-visual concept-visual kind-${kind}" data-concept-visual><div class="math-model-label">${esc(title)}</div><div class="concept-diagram" data-concept-diagram>${diagram}</div><div class="concept-options">${parts.map((part,index)=>`<button type="button" data-concept-option="${index}" class="${index===0?'is-active':''}">${part}</button>`).join('')}</div><div class="visual-status" data-concept-status>先點選圖中的「${parts[0]}」，確認它在本節代表什麼。</div></div>`;
  }
  function mathModel(title){
    const models={
      '正負數與絕對值':['數線與距離模型','把滑鼠點在數線左右兩端：位置代表正負，離 0 的格數才是絕對值。','−4　−3　−2　−1　0　1　2　3　4'],
      '整數的加減':['數線移動模型','從第一個數出發；加正往右、加負往左。減法先改寫成「加上相反數」。','起點 −2　→　加 (+5)　→　終點 3'],
      '整數的乘除':['符號決策表','先看兩個數的符號：同號得正、異號得負；再做絕對值的乘除。','(＋)×(＋)=＋　(＋)×(−)=−　(−)×(−)=＋'],
      '指數律':['重複相乘方塊','指數不是乘上一個數，而是底數重複相乘的次數。','2³ = 2 × 2 × 2 = 8'],
      '科學記號':['小數點尺度尺','讓第一個非零數字落在個位；小數點向左移，10 的指數為正。','3,200,000　→　3.2 × 10⁶'],
      '質因數分解':['因數樹','一路拆成質數；葉端相乘必須回到原數。','60　→　2 × 30　→　2 × 2 × 15　→　2² × 3 × 5'],
      '最大公因數與最小公倍數':['共同質因數圈選','共同擁有的質因數取較小次方找最大公因數；全部取較大次方找最小公倍數。','12=2²×3　　18=2×3²'],
      '分數的加減':['同一單位的分數條','分母代表每一份的大小，先通分成相同單位，才可相加減。','1／3　＋　1／6　→　2／6 ＋ 1／6 = 3／6'],
      '分數的乘除':['面積與倒數模型','分數乘法是取「其中的其中」；除以分數改成乘它的倒數。','2／3 × 3／4 = 6／12 = 1／2'],
      '式子的運算':['代數積木','只有同類項能合併；字母與次方相同才算同類項。','3x + 2x − 4　→　5x − 4'],
      '解一元一次方程式':['等式天平','等號兩邊每次做完全相同的運算；目標是讓 x 單獨留在一邊。','3x − 5 = 10　→　3x = 15　→　x = 5'],
      '一元一次方程式應用':['情境翻譯流程','先定義未知數，再把每個句子改成數量關係式，最後代回驗算。','設 x 為單價　→　數量 × x = 總價']
      ,'乘法公式':['面積拼圖','把 (a＋b)² 想成邊長 a＋b 的正方形：a²、2ab、b² 三塊面積相加。','(a＋b)² = a²＋2ab＋b²']
      ,'多項式運算':['分配律展開圖','括號外每一項都要乘進去；合併前先確認是不是同類項。','2(x＋3)−x = 2x＋6−x = x＋6']
      ,'平方根':['面積反推','若正方形面積是 49，邊長是 7；√49 代表非負的主平方根。','√49 = 7；(−7)² = 49']
      ,'畢氏定理':['直角三角形拼圖','只適用直角三角形：兩股平方和等於斜邊平方。','a²＋b² = c²']
      ,'一元二次方程式':['乘積為零門檻','先整理成一邊為 0；兩因式相乘為 0，至少一個因式為 0。','(x−2)(x＋3)=0　→　x=2 或 −3']
      ,'統計圖表':['資料中心尺','平均數看總量分配；中位數看排序中間；眾數看出現最多。','先看資料是否有極端值，再選適合的代表值']
      ,'機率':['等可能分母盤','機率＝符合條件的結果數／所有等可能結果數。','P(事件)=有利結果÷全部結果']
      ,'二元一次方程式圖形':['直線交點','同時滿足兩式的數對，就是兩條直線的交點。','y=2x＋1 與 y=−x＋4 的交點']
      ,'比例與函數':['變量連線','正比 y=kx 通過原點；反比 xy=k，x 增大時 y 變小。','正比：y／x 固定；反比：xy 固定']
      ,'二次函數':['拋物線三把尺','a 決定開口與寬窄；h、k 決定頂點 (h,k) 與對稱軸 x=h。','y=a(x−h)²＋k']
      ,'二次函數應用':['極值定位','先看開口方向，再找頂點；向上頂點是最小值，向下是最大值。','頂點 → 對稱軸 → 交點／範圍']
      ,'相似形':['對應比例表','先排好對應頂點順序；角相等、對應邊成同一比例。','△ABC ∼ △DEF　→　AB／DE=BC／EF']
      ,'圓':['同弧角度圖','同弧的圓心角是圓周角兩倍；先圈出同一段弧。','圓心角 = 2 × 圓周角']
      ,'三角比':['直角三角形標邊','相對指定角：sin=對／斜，cos=鄰／斜，tan=對／鄰。','tan θ = 對邊／鄰邊']
      ,'生活測量':['仰角觀測圖','把水平線、視線與高度畫成直角三角形，保留單位。','tan θ = 高度／水平距離']
      ,'統計與資料判讀':['資料可信度檢查','先檢查來源、樣本、時間、單位與縱軸刻度，才解讀趨勢。','圖大不等於差距大；先看刻度']
      ,'機率模型':['樹狀圖分支','多步驟事件沿樹狀圖相乘；互斥結果再相加。','P(A且B)=P(A)×P(B|A)']
    }; const m=models[title]||['數學關係圖','先把已知條件放進圖或式子，讓關係變得可見。',title];
    if(title==='正負數與絕對值') return absoluteValueLab();
    if(title==='整數的加減') return integerAdditionLab();
    if(title==='整數的乘除') return signRuleLab();
    if(title==='指數律'||title==='科學記號') return exponentLab(title);
    if(title==='質因數分解'||title==='最大公因數與最小公倍數') return factorLab(title);
    if(title==='式子的運算'||title==='多項式運算'||title==='乘法公式') return algebraLab(title);
    if(['直角坐標平面','二元一次方程式的圖形','二元一次方程式圖形','比例式','正比與反比','比例與函數','二次函數','二次函數應用'].includes(title)) return coordinateLab(title);
    if(['平方根','畢氏定理','相似形','圓','三角比','生活測量'].includes(title)) return geometryLab(title);
    if(['統計圖表','統計與資料判讀','機率','機率模型'].includes(title)) return dataLab(title);
    if(['解一元一次方程式','一元一次方程式應用','二元一次方程式','二元一次聯立方程式','聯立方程式應用','一元二次方程式'].includes(title)) return balanceLab(title);
    if(title==='一元一次不等式') return inequalityLab();
    if(['食物中的養分','酵素與消化','動物如何獲得養分','植物的運輸構造','神經系統與反應','內分泌與恆定','體溫與水分恆定','生殖的基礎','遺傳與基因','演化與分類','生態系與能量流動','神經與恆定','遺傳與演化'].includes(title)) return bodySystemLab(title);
    if(title==='分數的加減'||title==='分數的乘除') return `${fractionLab(title)}<details class="visual-caption"><summary>${m[0]}：操作提示</summary><p>${m[1]}</p><code>${m[2]}</code></details>`;
    const kind=window.INTERACTIVE_SPECS?.get('數學',title); if(!kind) throw Error(`缺少數學互動模型規格：${title}`);
    return `${mathVisual(title,m[2],m[1],kind)}<details class="visual-caption"><summary>${m[0]}：操作提示</summary><p>${m[1]}</p><code>${m[2]}</code></details>`;
  }
  function scienceModel(title){
    const models={
      '探究自然的方法':['探究迴圈','觀察 → 問題 → 假設 → 實驗 → 資料 → 結論'],
      '基本測量':['測量資料鏈','選工具與單位 → 估讀刻度 → 重複測量 → 記錄不確定性'],
      '生命現象與生物圈':['生命條件網','能量、反應、生長、生殖、感應與環境相連'],
      '細胞的構造':['細胞工廠','細胞膜管進出、細胞質是場所、細胞核含遺傳訊息'],
      '物質進出細胞':['濃度平衡箭頭','粒子由多往少擴散；水分依濃度差滲透'],
      '生物體的組成層次':['生命階梯','細胞 → 組織 → 器官 → 器官系統 → 個體'],
      '食物中的養分':['養分任務卡','醣類脂質供能；蛋白質建構；維生素與礦物質調節'],
      '酵素與消化':['鎖鑰模型','專一受質配合活性部位；溫度、酸鹼影響活性'],
      '植物如何製造養分':['光合作用路徑','二氧化碳＋水 ─光／葉綠體→ 養分＋氧氣'],
      '動物如何獲得養分':['消化管旅行','攝取 → 消化 → 吸收 → 運輸 → 細胞利用'],
      '植物的運輸構造':['雙向運輸管','木質部主要運水與礦物質；韌皮部運送有機養分'],
      '動物的血液循環':['雙循環箭頭','全身 → 右心 → 肺 → 左心 → 全身'],
      '神經系統與反應':['刺激反應線','刺激 → 受器 → 神經 → 中樞 → 反應器'],
      '神經與恆定':['恆定控制迴圈','刺激／偏離 → 受器 → 調節中樞 → 反應器 → 回到適當範圍'],
      '內分泌與恆定':['負回饋迴圈','偏離適當值 → 調節反應 → 回到範圍'],
      '體溫與水分恆定':['恆定儀表板','流汗散熱、血管舒張／收縮與水分調節'],
      '遺傳與基因':['性狀棋盤格','親代配子組合 → 子代基因型 → 表現型比例'],
      '演化與分類':['族群時間線','遺傳變異 → 生存繁殖差異 → 世代比例改變'],
      '生態系與能量流動':['食物網箭頭','能量由被吃者流向吃者；物質可循環'],
      '物質與密度':['密度積木','密度＝質量÷體積；同體積比質量、同質量比體積'],
      '聲音與波動':['波形讀值','振幅影響響度；頻率影響音調；需要介質傳遞'],
      '光與色彩':['光路圖','反射角等於入射角；折射因光速改變而偏折'],
      '溫度與熱':['熱傳三箭頭','傳導、對流、輻射由高溫處往低溫處傳熱'],
      '化學反應':['粒子重組','反應前後原子數守恆；新物質來自重新排列'],
      '酸鹼與指示劑':['pH 光譜','pH 小於 7 酸性，大於 7 鹼性，以 7 為中性基準'],
      '酸鹼鹽':['離子與中和','酸、鹼以 pH 判讀；中和是酸鹼性趨近中性，不是憑顏色猜測'],
      '力與運動':['受力箭頭','合力決定加速度；速度變化代表運動狀態改變'],
      '壓力、浮力與機械':['力的分配','壓力＝力÷面積；浮力與排開液體有關'],
      '電與能量':['電路閉環','電流需完整迴路；能量在元件間轉換'],
      '能源轉換':['能量帳本','輸入能量 → 有用輸出＋損耗；比較效率、安全與環境代價'],
      '電流與磁場':['電磁場環','通電導線周圍有磁場；線圈與鐵芯可增強效果'],
      '板塊與地質':['板塊邊界','聚合、張裂、錯動造成地震、火山與地形'],
      '天文與永續':['日地月與取捨','用運動模型解釋天文現象，再以環境、社會、經濟評估方案'],
      '天文與永續':['系統取捨圖','自然證據、生活需求、社會成本需一起評估']
    }; const m=models[title]||Object.entries(models).find(([key])=>title.includes(key)||key.includes(title))?.[1]||['科學因果流程','條件 → 機制 → 可觀察結果'];
    if(title==='動物的血液循環'&&window.heartAnatomyLab) return window.heartAnatomyLab();
    if(['生命現象與生物圈','細胞的構造','物質進出細胞','生物體的組成層次'].includes(title)) return cellLab(title);
    if(['探究自然的方法','基本測量','物質與密度','化學反應','酸鹼與指示劑','酸鹼鹽','化學反應速率','聲音與波動','光與色彩','溫度與熱','力與運動','壓力、浮力與機械','電與能量','電流與磁場','能源轉換','板塊與地質','天文與永續'].includes(title)) return scienceLab(title);
    const kind=window.INTERACTIVE_SPECS?.get('自然',title);if(!kind)throw Error(`缺少自然互動模型規格：${title}`);
    return `${conceptVisual('自然',kind,title,m[1])}<details class="visual-caption"><summary>${m[0]}：觀察提示</summary><p>${m[1]}</p></details>`;
  }
  function languageModel(subject,title){
    const en={
      '自我介紹與人稱代名詞':['人稱配對','I／you／we／they ↔ am／are；he／she／it ↔ is'], '日常作息與現在簡單式':['習慣時間線','every day、usually → 主詞＋原形／第三人稱單數'], '正在發生與現在進行式':['現在進行燈號','now、at the moment → am／is／are＋V-ing'], '名詞、冠詞與數量':['名詞分類籃','可數單數用 a／an；複數或不可數量用 some／any'], '地點與介系詞':['位置地圖','in 在裡面；on 在表面；at 指特定點'], '問句與簡答':['問答樹','be 動詞直接倒裝；一般動詞用 Do／Does'], '過去式與時間線':['過去事件軸','yesterday、last… → 規則 ed 或不規則過去式'], '比較級與最高級':['比較階梯','兩者比較＋than；三者以上用 the 最高級'], '未來計畫與 be going to':['未來箭頭','已有計畫或明顯跡象 → be going to'], '情態助動詞':['語氣儀表板','can 能力／允許；should 建議；must 必要'], '連接詞':['邏輯接線','because 原因；so 結果；but 轉折'], '被動語態入門':['動作焦點切換','承受動作的主詞＋be＋p.p.'], '現在完成式':['過去連到現在','have／has＋p.p. 表經驗、完成或持續'], '關係子句':['名詞標籤','先行詞是人用 who；事物用 which'], '篇章連接':['段落箭頭','however 轉折；therefore 結果'], '推論閱讀':['證據放大鏡','合理推論必須回到文本線索'], '會考寫作':['寫作骨架','任務點 → 段落 → 例子 → 檢查']};
    Object.assign(en,{'不定詞與動名詞':['動詞搭配箭頭','先看前面的動詞；不同搭配決定 to V 或 V-ing'],'分詞與長句':['長句切片','先找主詞＋主要動詞，再把分詞與補充資訊括起來'],'閱讀圖表':['欄位交叉表','先找題目任務，再對照時間、數字與限制詞'],'情境對話':['角色回應卡','先判斷請求、邀請、道歉或建議，再選符合角色的回應'],'段落寫作':['段落三明治','主題句 → 具體細節 → 收束或連接下一句'],'圖表與公告':['任務掃描','圈出人物、時間、地點、價格、not／except 等限制']});
    const zh={
      '字音、字形與詞義':['語境三角形','部首、詞性、前後搭配一起判讀'], '成語與詞語運用':['固定語意盒','成語先整體換白話，再放回句子檢查'], '句型、語法與標點':['句子骨架','找主詞、主要動詞、受詞與修飾語'], '修辭與表達效果':['手法到效果','手法 → 畫面／語氣 → 作者情感'], '記敘文本閱讀':['事件路線','人物 → 事件 → 轉折 → 感受'], '說明文本閱讀':['說明工具箱','定義、分類、因果、舉例各有任務'], '議論文本閱讀':['論證三角','主張 ← 理由 ← 可查證證據'], '文言文句意':['古文解碼','人物／動詞／轉折 → 補省略 → 重組白話'], '古典詩歌意象':['景情連線','景物與動作如何烘托心情'], '跨文本與圖表':['資料比較表','來源、時間、對象、單位、結論逐項比較'], '寫作表達':['段落地圖','中心句 → 細節／例子 → 回扣題目'], '論證閱讀':['主張檢驗台','證據是否足夠？是否有替代原因？'], '國學常識':['背景索引','作品、體裁、稱謂與時代協助閱讀'], '會考閱讀策略':['題幹回查法','先讀任務，再回原文找直接證據']};
    Object.assign(zh,{'字詞與語法':['詞性定位','先辨名詞、動詞、形容詞在句中扮演的角色'],'古典詩文':['古文解碼','人物／動詞／轉折 → 補省略 → 重組白話'],'文言統整':['古文關係網','實詞、虛詞、句式與人物關係要一起判讀'],'抒情文本':['經驗到情感','具體事件與景物如何承載情緒'],'議論寫作':['立場建築','主張 → 理由 → 例證 → 回應不同意見'],'說明與圖表':['圖文對照','文字說明與圖表的單位、範圍必須一起讀'],'修辭應用':['手法到效果','手法 → 畫面／語氣 → 作者情感'],'文言虛詞':['虛詞定位','從前後詞語關係判斷之、其、以、於的功能'],'寫作組織':['段落地圖','中心句 → 細節／例子 → 回扣題目'],'閱讀推論':['證據邊界','只推出文本支持的結論，不加入自己的想像'],'資料判讀':['資料可信度','先檢查單位、樣本、時間與圖表刻度']});
    const m=(subject==='英文'?en:zh)[title]||['語言結構圖','線索 → 結構 → 完整意思'];
    if(subject==='英文'){const englishKind=window.INTERACTIVE_SPECS?.get(subject,title);if(englishKind) return englishLab(title,englishKind);}
    if(subject==='國文'){const chineseKind=window.INTERACTIVE_SPECS?.get(subject,title);if(chineseKind) return chineseLab(title,chineseKind);}
    const kind=window.INTERACTIVE_SPECS?.get(subject,title);if(!kind)throw Error(`缺少${subject}互動模型規格：${title}`);
    return `${conceptVisual(subject,kind,title,m[1])}<details class="visual-caption"><summary>${m[0]}：操作提示</summary><p>${m[1]}</p></details>`;
  }
  function socialModel(title){
    const models={'臺灣的自然環境':['臺灣環境層疊圖','位置 → 地形 → 氣候 → 災害與人類調適'],'史前與原住民族':['史料拼圖','考古資料與口傳文化 → 多元族群的生活方式'],'荷西與鄭氏時期':['海洋貿易網','外來政權／貿易 → 統治制度 → 移民與社會改變'],'清代臺灣的治理':['開墾治理線','移民與土地利用 → 行政治理 → 社會結構'],'開港與近代化':['港口連線','通商開港 → 商品與人口流動 → 城市與制度改變'],'近代臺灣與東亞':['區域連動圖','外部局勢 → 地方制度 → 人民生活與回應'],'中國近代變遷':['內外壓力圖','內部問題＋外來衝擊 → 改革／革命 → 社會變遷'],'世界近代史':['工業全球鏈','工業化 → 帝國擴張與交流 → 區域影響'],'現代臺灣':['現代轉型線','民主化／經濟轉型／社會運動 → 權利與生活改變'],'世界現代史':['全球事件網','冷戰／科技／全球化 → 不同地區的連動'],'地圖與地理資訊':['讀圖四步','標題與時間 → 圖例與單位 → 方向比例尺 → 空間判讀'],'臺灣的位置與區域':['區域定位圖','經緯位置＋鄰近區域 → 交通、交流與戰略意義'],'人口與聚落':['人口分布因果','自然條件＋工作機會＋交通 → 人口密度與聚落'],'產業活動與區位':['產業選址表','原料／勞力／交通／市場／政策 → 區位選擇'],'資源與環境問題':['人地回饋圈','資源利用 → 環境影響 → 保育與調適'],'中國與東亞地理':['區域比較尺','位置、地形、氣候、水資源 → 人口與產業'],'人口與產業':['區位證據表','資源、交通、市場、勞力、政策 → 發展差異'],'世界區域地理':['區域比較表','自然環境 → 人文活動 → 區域特色'],'全球化與環境':['跨境流動線','商品、資本、資訊、人口 → 受益與代價'],'永續發展':['三面向天平','環境保護 ↔ 社會公平 ↔ 經濟可行'],'社會生活與規範':['規範同心圓','生活行為 → 道德／社會規範／法律 → 後果'],'人性尊嚴與權利':['權利界線','個人權利 ↔ 他人權利與公共利益'],'家庭與校園生活':['角色關係圖','不同角色 → 權利、義務、溝通與責任'],'社區參與':['公共事務流程','問題 → 蒐集意見與資料 → 參與／監督 → 改善'],'政府與公共服務':['公共服務鏈','共同需求 → 政府資源與程序 → 公共服務'],'媒體與資訊識讀':['資訊檢核漏斗','來源 → 發布時間 → 證據 → 立場與查證'],'法律與生活':['法律案例圖','行為人／事實 → 權利義務 → 規範與程序'],'政府與民主':['權力制衡圖','人民授權 → 政府權力 → 監督與權利保障'],'市場與金融':['市場互動圖','需求／供給 → 價格訊號 → 生產與消費選擇'],'民主政治':['民主運作環','選舉與參與 → 多數決 → 少數權利與監督'],'公共參與':['理性參與鏈','可查證資料 → 理由 → 程序 → 公共決策'],'法律與權利救濟':['救濟路徑','權利受影響 → 依程序申訴／救濟 → 公平處理'],'跨科公共議題':['跨科決策盤','自然證據＋數學資料＋制度程序＋價值取捨']};
    const m=models[title]|| (title.includes('地圖')||title.includes('地理')||title.includes('區域')||title.includes('人口')||title.includes('產業')||title.includes('環境')||title.includes('全球化')||title.includes('永續')?['地圖判讀順序','標題／時間 → 圖例／單位 → 空間分布 → 人地原因']:title.includes('政府')||title.includes('法律')||title.includes('權利')||title.includes('民主')||title.includes('公共')||title.includes('市場')||title.includes('金融')?['公民案例關係圖','行為人／受影響者 → 權利義務 → 規則程序 → 結果']:['歷史因果時間線','背景條件 → 事件／制度 → 不同群體的影響']);
    const kind=window.INTERACTIVE_SPECS?.get('社會',title);if(!kind)throw Error(`缺少社會互動模型規格：${title}`);
    if(title!=='臺灣的自然環境') return socialLab(title,kind);
    return `${conceptVisual('社會',kind,title,m[1])}<details class="visual-caption"><summary>${m[0]}：操作提示</summary><p>${m[1]}</p></details>`;
  }
  function stage(subject,title,goal){
    if(subject==='數學') return mathModel(title);
    if(subject==='自然') return scienceModel(title);
    if(subject==='英文'||subject==='國文') return languageModel(subject,title);
    if(subject==='社會') return socialModel(title);
    const labels=subject==='英文'?['情境線索','句型與字詞','完整意思']:subject==='國文'?['文本線索','作者意圖','有據的判讀']:['背景條件','事件／制度','群體影響'];
    return `<div class="flow-model">${labels.map((x,i)=>`<span class="flow-node">${x}</span>${i<labels.length-1?'<span class="flow-arrow">→</span>':''}`).join('')}</div><small>把「${title}」放入這條路徑，逐格說出它如何發生、如何被判斷。</small>`;
  }
  function render(){
    if(q('.chapter-lab')) return;
    const meta=q('.lesson-layout .eyebrow'),titleEl=q('.lesson-title'),concept=q('.concept'); if(!meta||!titleEl||!concept||!titleEl.textContent.includes('｜')) return;
    const [subject]=meta.textContent.split(' · '), title=titleEl.textContent.split('｜').slice(1).join('｜').trim(), goal=concept.textContent.replace('本節學習目標：','').trim(), a=subjectAdvice[subject]; if(!a) return;
    const section=document.createElement('section'); section.className='chapter-lab';
    const source=sourceGuide[subject];section.innerHTML=`<header><div class="eyebrow">${a.mode}｜互動式分節教材</div><h2>${title}</h2><p>${goal}</p></header><div class="chapter-workspace"><div class="model-stage" data-model>${stage(subject,title,goal)}</div><aside class="lab-panel"><h3>先做預測</h3><div class="prediction">看到題目時，先不要選答案。請說出：<b>我會先找哪個條件？它和本節概念有什麼關係？</b></div><div class="chapter-choices"><button data-chapter-choice="0">先把題目中的條件標記出來</button><button data-chapter-choice="1">只靠記得的關鍵字猜答案</button><button data-chapter-choice="2">先建立模型／關係，再驗證結論</button></div><div class="chapter-feedback" data-chapter-feedback>點選一個做法，查看解題理由。</div></aside></div><details class="chapter-note-details"><summary>操作後再看：重點、解題法與常見誤解</summary><div class="chapter-note-grid"><article><b>圖像化重點</b><p>${goal}</p></article><article><b>解題整理法</b><p>${a.method}</p></article><article><b>常見誤解</b><p>${a.trap}</p></article></div><div class="source-note"><b>本節整理依據</b><p>${source[0]}</p><a href="${source[1]}" target="_blank" rel="noopener">查看公開筆記的章節整理方式</a><small>本站只參考整理方法與章節脈絡；概念說明、圖示、題目與解答均自行撰寫。</small></div></details><button class="chapter-replay" data-chapter-replay>重新播放圖像路徑</button>`;
    (q('.heart-lab')||q('.visual-box')||q('.concept'))?.after(section);
    const absLab=q('[data-absolute-lab]',section); if(absLab) renderAbsolute(absLab);
    const integerLab=q('[data-integer-lab]',section); if(integerLab) renderInteger(integerLab);
    const fractionLabEl=q('[data-fraction-lab]',section); if(fractionLabEl) renderFraction(fractionLabEl);
    const signLab=q('[data-sign-rule-lab]',section); if(signLab) renderSignRule(signLab);
    const exponentLabEl=q('[data-exponent-lab]',section); if(exponentLabEl) renderExponent(exponentLabEl);
    const factorLabEl=q('[data-factor-lab]',section); if(factorLabEl) renderFactor(factorLabEl);
    const algebraLabEl=q('[data-algebra-lab]',section); if(algebraLabEl) renderAlgebra(algebraLabEl);
    const coordinateLabEl=q('[data-coordinate-lab]',section); if(coordinateLabEl) renderCoordinate(coordinateLabEl);
    const geometryLabEl=q('[data-geometry-lab]',section); if(geometryLabEl) renderGeometry(geometryLabEl);
    const dataLabEl=q('[data-data-lab]',section); if(dataLabEl) renderData(dataLabEl);
    const bodyLabEl=q('[data-body-system-lab]',section); if(bodyLabEl) renderBodySystem(bodyLabEl);
    const scienceLabEl=q('[data-science-lab]',section); if(scienceLabEl) renderScience(scienceLabEl);
    const englishLabEl=q('[data-english-lab]',section); if(englishLabEl) renderEnglish(englishLabEl);
    const chineseLabEl=q('[data-chinese-lab]',section); if(chineseLabEl) renderChinese(chineseLabEl);
    const socialLabEl=q('[data-social-lab]',section); if(socialLabEl) renderSocial(socialLabEl);
    const balanceLabEl=q('[data-balance-lab]',section); if(balanceLabEl) renderBalance(balanceLabEl);
    const cellLabEl=q('[data-cell-lab]',section); if(cellLabEl) renderCell(cellLabEl);
    const inequalityLabEl=q('[data-inequality-lab]',section); if(inequalityLabEl) renderInequality(inequalityLabEl);
    const taiwanLab=q('[data-taiwan-lab]',section); if(taiwanLab) renderTaiwanLab(taiwanLab);
    const photoLab=q('[data-photo-lab]',section); if(photoLab) renderPhotosynthesisLab(photoLab);
  }
  app.addEventListener('click',e=>{
    const lab=e.target.closest('.chapter-lab'); if(!lab)return;
    const choice=e.target.closest('[data-chapter-choice]'); if(choice){lab.querySelectorAll('[data-chapter-choice]').forEach(b=>b.classList.toggle('active',b===choice));q('[data-chapter-feedback]',lab).textContent=choice.dataset.chapterChoice==='1'?'這樣容易被陷阱帶走。請回到題目的條件，確認它真能支持結論。':'正確方向：先從條件建立關係，再把結論放回題目檢查是否合理。';}
    if(e.target.closest('[data-chapter-replay]')) replayLab(lab);
    const node=e.target.closest('[data-visual-node]'); if(node){const visual=node.closest('[data-visual]');const nodes=[...visual.querySelectorAll('[data-visual-node]')];const current=Number(node.dataset.visualNode);nodes.forEach((item,index)=>item.classList.toggle('is-active',index<=current));q('[data-visual-status]',visual).textContent=`第 ${current+1} 步已亮起：${node.textContent.trim()}。現在請說出它如何連到下一步。`;}
    const mathStep=e.target.closest('[data-math-step]'); if(mathStep){const visual=mathStep.closest('[data-math-visual]');const messages=['先把題目的數、圖形或條件圈出來。','把同一類量連線：確認符號、單位或對應關係。','把答案代回原條件或圖像，檢查是否合理。'];visual.querySelectorAll('[data-math-step]').forEach((button,index)=>button.classList.toggle('is-active',index===Number(mathStep.dataset.mathStep)));q('[data-math-status]',visual).textContent=messages[Number(mathStep.dataset.mathStep)];}
    const conceptOption=e.target.closest('[data-concept-option]');if(conceptOption){const visual=conceptOption.closest('[data-concept-visual]'),options=[...visual.querySelectorAll('[data-concept-option]')],index=Number(conceptOption.dataset.conceptOption);options.forEach((button,i)=>button.classList.toggle('is-active',i===index));q('[data-concept-status]',visual).textContent=`已選取「${conceptOption.textContent}」：請在圖中找出它，接著再點下一個步驟。`;q('[data-concept-diagram]',visual).dataset.step=String(index);}
    const layer=e.target.closest('[data-taiwan-layer]');if(layer){const visual=layer.closest('[data-taiwan-lab]');visual.querySelectorAll('[data-taiwan-layer]').forEach(button=>button.classList.toggle('is-active',button===layer));renderTaiwanLab(visual,layer.dataset.taiwanLayer);}
    const signButton=e.target.closest('[data-sign-a],[data-sign-b]');if(signButton){const visual=signButton.closest('[data-sign-rule-lab]');if(signButton.dataset.signA)visual.dataset.a=signButton.dataset.signA;if(signButton.dataset.signB)visual.dataset.b=signButton.dataset.signB;visual.querySelectorAll('[data-sign-a]').forEach(b=>b.classList.toggle('is-active',b===signButton&&signButton.dataset.signA!==undefined));visual.querySelectorAll('[data-sign-b]').forEach(b=>b.classList.toggle('is-active',b===signButton&&signButton.dataset.signB!==undefined));renderSignRule(visual);}
    const englishChoice=e.target.closest('[data-english-choice]');if(englishChoice){const visual=englishChoice.closest('[data-english-lab]');visual.querySelectorAll('[data-english-choice]').forEach(b=>b.classList.toggle('is-active',b===englishChoice));renderEnglish(visual,Number(englishChoice.dataset.englishChoice));}
    const chineseChoice=e.target.closest('[data-chinese-choice]');if(chineseChoice){const visual=chineseChoice.closest('[data-chinese-lab]');visual.querySelectorAll('[data-chinese-choice]').forEach(b=>b.classList.toggle('is-active',b===chineseChoice));renderChinese(visual,Number(chineseChoice.dataset.chineseChoice));}
    const socialChoice=e.target.closest('[data-social-choice]');if(socialChoice){const visual=socialChoice.closest('[data-social-lab]');visual.querySelectorAll('[data-social-choice]').forEach(b=>b.classList.toggle('is-active',b===socialChoice));renderSocial(visual,Number(socialChoice.dataset.socialChoice));}
    const inequalityChoice=e.target.closest('[data-inequality-dir]');if(inequalityChoice){const visual=inequalityChoice.closest('[data-inequality-lab]');visual.dataset.inequalityDir=inequalityChoice.dataset.inequalityDir;visual.querySelectorAll('[data-inequality-dir]').forEach(b=>b.classList.toggle('is-active',b===inequalityChoice));renderInequality(visual);}
  });
  app.addEventListener('input',e=>{const abs=e.target.closest('[data-absolute-lab]');if(abs&&e.target.matches('[data-absolute-slider]'))renderAbsolute(abs);const integer=e.target.closest('[data-integer-lab]');if(integer&&e.target.matches('[data-integer-start],[data-integer-change]'))renderInteger(integer);const fraction=e.target.closest('[data-fraction-lab]');if(fraction&&e.target.matches('[data-fraction-a],[data-fraction-b],[data-fraction-c],[data-fraction-d]'))renderFraction(fraction);const exponent=e.target.closest('[data-exponent-lab]');if(exponent&&e.target.matches('[data-exponent-base],[data-exponent-count]'))renderExponent(exponent);const factor=e.target.closest('[data-factor-lab]');if(factor&&e.target.matches('[data-factor-a],[data-factor-b]'))renderFactor(factor);const algebra=e.target.closest('[data-algebra-lab]');if(algebra&&e.target.matches('[data-algebra-a],[data-algebra-b]'))renderAlgebra(algebra);const coordinate=e.target.closest('[data-coordinate-lab]');if(coordinate&&e.target.matches('[data-coordinate-a],[data-coordinate-b]'))renderCoordinate(coordinate);const geometry=e.target.closest('[data-geometry-lab]');if(geometry&&e.target.matches('[data-geometry-a],[data-geometry-b]'))renderGeometry(geometry);const data=e.target.closest('[data-data-lab]');if(data&&e.target.matches('[data-data-a],[data-data-b]'))renderData(data);const body=e.target.closest('[data-body-system-lab]');if(body&&e.target.matches('[data-body-input],[data-body-capacity]'))renderBodySystem(body);const science=e.target.closest('[data-science-lab]');if(science&&e.target.matches('[data-science-input],[data-science-limit]'))renderScience(science);const balance=e.target.closest('[data-balance-lab]');if(balance&&e.target.matches('[data-balance-x]'))renderBalance(balance);const cell=e.target.closest('[data-cell-lab]');if(cell&&e.target.matches('[data-cell-out],[data-cell-in]'))renderCell(cell);const photo=e.target.closest('[data-photo-lab]');if(photo&&e.target.matches('[data-photo-light],[data-photo-water],[data-photo-co2]'))renderPhotosynthesisLab(photo);});
  app.addEventListener('input',e=>{const inequality=e.target.closest('[data-inequality-lab]');if(inequality&&e.target.matches('[data-inequality-value]'))renderInequality(inequality);});
  new MutationObserver(render).observe(app,{childList:true,subtree:true}); render();
})();
